DROP TABLE IF EXISTS Customers;

CREATE TABLE Customers (
  NetID varchar(255) NOT NULL,
  Name varchar(255) default NULL,
  Email varchar(255) default NULL,
  Password varchar(255),
  Credibility varchar(30) default NULL,
  PRIMARY KEY (NetID)
);

INSERT INTO Customers (NetID,Name,Email,Password)
VALUES
  ("FGHMCDM053","Heather Sims","erat.volutpat.nulla@protonmail.com","EXB18NCF7OI"),
  ("DCQWOCY282","Ezra Jacobson","nec.enim.nunc@google.edu","ANP45LUY3VG"),
  ("GYRKSDC760","Baker Castaneda","donec.luctus@aol.edu","KTV65KTB6TD"),
  ("WDUPPIR973","Clementine Leach","nulla.integer@aol.com","YLW77KZL7KF"),
  ("OWBSEIX408","Kimberly Cohen","viverra@yahoo.org","TTM37BJD2EJ"),
  ("SLRGBRC576","Alexander Holcomb","libero.integer@google.couk","YOV57FVY6AF"),
  ("XQFUPCI388","Griffin Russell","aliquam.nec@outlook.org","JOF16JBO3MH"),
  ("SGUQOJG855","Knox Griffith","nisi.nibh@icloud.edu","XXP41YMY4PE"),
  ("NPCTXHQ717","Preston Decker","quam.quis@protonmail.edu","WXH25WXK7MR"),
  ("GROOJKN364","Jolene Porter","tempus.eu@aol.com","NVE85EIJ7UX"),
  ("LJIZJEB426","Libby Flynn","ligula.aenean@protonmail.com","ATT88GEZ3BW"),
  ("XUSFUVZ754","Fay Jordan","risus.quis@aol.com","HEP67BLY6OO"),
  ("RROLWHT881","Bell Summers","urna@protonmail.com","YRX81NUX0LX"),
  ("PKELHXF059","Logan Bond","ligula@yahoo.com","RMT49LZS6EI"),
  ("OFDTTJG526","Darrel Giles","lectus@yahoo.net","TUG75QDU2NV"),
  ("VZSETPB338","Mona Small","est.mauris@hotmail.com","FIG63NSB3BM"),
  ("NMWAOWL568","Marsden Weber","eget.laoreet@aol.ca","IGF08UKE2NV"),
  ("WJQWUGK845","Keaton Glenn","augue.porttitor@icloud.couk","LDQ52HDY9UU"),
  ("CIVWQQI127","Aretha Mueller","vestibulum.ut@hotmail.couk","ZND75UPC5IU"),
  ("EPNCPWN236","Katell Sampson","sed.nulla@icloud.org","QNK12MWU4UW");
INSERT INTO Customers (NetID,Name,Email,Password)
VALUES
  ("EFBPTEL288","Noah Pope","ligula.aenean@google.edu","BBJ62HQZ1JS"),
  ("KOUJGAX467","Geoffrey Bell","hendrerit@hotmail.com","IJZ46OMD1LS"),
  ("SBUOYNL871","Echo Hays","fringilla.cursus.purus@yahoo.edu","PXE08XNJ9MV"),
  ("URGTMRW333","Macon Wooten","quisque@google.com","JFG57QFT4IC"),
  ("PMMXBKU604","Megan Holcomb","eu@outlook.org","ZUC25HJU7EX"),
  ("MJHWGUJ441","Jordan Gould","enim.consequat@aol.org","FQN24VEP7UT"),
  ("PKCILEY440","Ursa Knox","quis.pede@protonmail.ca","TXA16GJF5VI"),
  ("LNKUJXB969","Courtney Carr","vestibulum@protonmail.net","BPW35BVA6WY"),
  ("QJKPWIR783","Isadora Moody","morbi.neque.tellus@google.org","BUL68EFD6JY"),
  ("MEWDADX565","Naida Hickman","vestibulum@aol.edu","YKO68NMB3TE"),
  ("ZNOGQRL347","Kevyn Suarez","mauris.elit.dictum@icloud.couk","DTN46ENF8IM"),
  ("CHCGYOG397","Silas Olson","morbi@yahoo.couk","NAL44QVH9RC"),
  ("LRCFIYS633","Zachary Chan","lobortis.quis@yahoo.edu","ZRI21WDX7CL"),
  ("TKEKTQT432","Zane Burke","mattis.ornare@yahoo.net","UQJ22LEN8PW"),
  ("BOKRVKN107","Kylee Dean","tempor.est.ac@google.ca","HJU92DCB3BS"),
  ("JEKEINK036","Kiara Carney","etiam.imperdiet@icloud.com","ENU11RSX0DG"),
  ("XODQQUD585","Ayanna Hines","est.mollis.non@hotmail.ca","FKC38FPR1SE"),
  ("WAROHCW995","Fay Boyle","feugiat.metus@aol.edu","BTT16NFZ9NT"),
  ("AKJRNQL806","Macey Logan","orci.in@outlook.com","XNJ42JBY7DE"),
  ("KOXRSBX165","Aristotle Potts","mauris.eu@yahoo.ca","WXD03WPQ7KJ");
INSERT INTO Customers (NetID,Name,Email,Password)
VALUES
  ("UEYBUFC606","Dawn Craft","congue@outlook.org","XVE77NHT9YA"),
  ("FWRDYES292","Ainsley Henderson","ipsum@icloud.edu","IET41JQH9FB"),
  ("SFIEJIW866","Dillon Durham","suspendisse.ac.metus@protonmail.net","LPS17FZS5YJ"),
  ("BNLIPRE670","Justin Hobbs","orci@protonmail.edu","GHK87SCN1VO"),
  ("KLTNXCS850","Kessie Sloan","nulla.eget.metus@protonmail.com","SNR46EYI2ST"),
  ("MMRLPGN588","Todd Chambers","vitae.sodales@outlook.ca","CIE73XFJ2JM"),
  ("OGFBVCV396","Kieran Hale","nunc.mauris.morbi@protonmail.couk","QGB64XBG5SW"),
  ("BFHJJTC633","Dustin Drake","in@aol.couk","ETI60RCB8BK"),
  ("RDKPWSA085","Deacon Molina","proin@icloud.com","HHX41GBS3GT"),
  ("WWWGZVX701","Ulla Hinton","urna.ut@yahoo.ca","YLT33SJT2RC");
INSERT INTO Customers (NetID,Name,Email,Password)
VALUES
  ("EBLSXQD638","Warren Barron","rhoncus.id.mollis@aol.edu","URC55BLA1TI"),
  ("KCHWJDS345","Eleanor Weber","risus.a.ultricies@hotmail.ca","UYQ64GNR2UO"),
  ("QUERMTL267","Cooper Conrad","rutrum@aol.org","TFH08ZNE8EH"),
  ("MQWQEGR443","Moses Shaw","ultrices@yahoo.ca","VGT22DEZ3DP"),
  ("UNCNOFU968","Sydney Owen","aliquet@google.net","HUC00WXK2NB"),
  ("UEVIBUZ171","Kennedy Ratliff","eget.tincidunt@hotmail.org","DTQ75RFR3MO"),
  ("DISRYFI426","Simon Rhodes","erat.in.consectetuer@icloud.net","FQK90TBP8UE"),
  ("LRNYCNT814","Ila Gilbert","malesuada@protonmail.edu","VMA23STT1HC"),
  ("BCHDGFL107","Philip Wall","dignissim.pharetra@google.ca","QJT45IUV2SW"),
  ("TJENGNC689","Zahir Andrews","in.condimentum@aol.net","OSS31JLW8GN"),
  ("DUVNMCB565","Jermaine Horne","duis.a@icloud.couk","DBR36YMG1TF"),
  ("EWVLVHE787","Lacy Wyatt","cursus.purus@google.couk","NTK00CNK2MK"),
  ("YVMMNEF806","Jerome Jarvis","consequat.enim@yahoo.org","DEN24FKV1AJ"),
  ("IYWNKTD334","Irene Sanders","proin.non@icloud.org","RKL40QHX7BN"),
  ("QWSTVBU828","Nicholas Jacobson","sed.pede.cum@outlook.org","UKS82KUW6LG"),
  ("YDIPSAL671","Sybil Bradshaw","dolor@google.edu","LBA53YHM8DP"),
  ("SLYWSXK967","Roth Hughes","vestibulum.neque.sed@outlook.couk","XGY51PXI6QC"),
  ("RBBMNFN417","Dante Rosales","nunc.in@aol.net","CQU21VFM5FW"),
  ("RJIMUVG414","Brock Mercer","donec.non@yahoo.net","SZK55QYJ9EZ"),
  ("DEDLYTY801","Patricia Salinas","cras.dictum@hotmail.couk","BSO51USE6NQ");
INSERT INTO Customers (NetID,Name,Email,Password)
VALUES
  ("GFPSUQL157","Hiram Alford","lectus.quis@protonmail.edu","XJT52SIM3AE"),
  ("HFLSQSG030","Ignatius Frazier","posuere.cubilia@icloud.ca","SUI03ODD5ZR"),
  ("QNAOBZX537","Katell Pate","vel.pede@aol.edu","ECB07HLV6NA"),
  ("HFOIXTQ443","Aaron Castro","metus@yahoo.org","DKL79ITI6VS"),
  ("SGNKSDC499","Giacomo Hines","fusce@yahoo.couk","WXY98CIB8TO"),
  ("KIMTOJH738","Lysandra Chen","mauris.suspendisse.aliquet@icloud.net","UBQ63PEY1ZS"),
  ("SZEHNBR247","Olivia Riggs","eget.ipsum@icloud.net","CXN88SUD3MV"),
  ("UBTHNZP884","Teegan Avery","suspendisse.tristique@hotmail.org","SKW84DFJ7EQ"),
  ("EYFQUSD537","Faith Johnston","interdum.nunc@aol.com","CBJ52YWP1AU"),
  ("YUJLNJG786","Neville Bartlett","a.malesuada@protonmail.ca","QHW34JSF7MW"),
  ("LYRURWE121","Abdul Doyle","morbi.quis@outlook.org","SQI55UHU7XG"),
  ("MXYRLXN576","Quin Jones","lorem.ipsum@hotmail.edu","SKH57SYS4EG"),
  ("DOPLGCK417","Kermit Whitaker","erat.vel.pede@outlook.org","HIR57QSB5NS"),
  ("YYPKPPP888","Adara Coffey","laoreet.lectus@icloud.com","BHM13TEL6SX"),
  ("XQIPBWU658","Quintessa Mcgowan","pharetra.sed@aol.org","XSK62FPQ7HD"),
  ("XRQUERV195","Fulton James","nibh.aliquam@protonmail.com","GTC28WYN3TL"),
  ("TSSMLPF838","Daphne Craig","augue.id.ante@icloud.org","VBB59BSF8LI"),
  ("IWURPGB781","Cameran Doyle","velit.cras.lorem@icloud.com","ENB48FWN2GU"),
  ("PCTOOTJ453","Bree Holmes","faucibus.ut@outlook.ca","TOK57PBO5KE"),
  ("HFBQHTX271","Kim Pacheco","nunc@icloud.com","HRY45VJX4EB");
INSERT INTO Customers (NetID,Name,Email,Password)
VALUES
  ("ZZGNZND701","Arden Estes","condimentum@google.ca","FKE62WTB1LR"),
  ("IYKADWL361","Colton Weber","blandit.congue@aol.org","SAM18VHJ3YQ"),
  ("YSLJLBW786","Ezekiel Moreno","sed.pede@google.com","RPZ56LSU7TC"),
  ("UIUUPRU497","Deborah Morse","neque.morbi@outlook.org","VCO77DVR6CA"),
  ("BRTYDOP476","Lisandra Farrell","per@google.edu","SSE46IOZ7EO"),
  ("RUSKDJM013","Flynn Moore","felis.adipiscing@hotmail.couk","WXI78WGK5RN"),
  ("VYGLYFD627","Clare Bond","posuere.cubilia.curae@yahoo.couk","FJR44BMM2GJ"),
  ("ECNXDWD557","Claudia Wiley","consectetuer.adipiscing@protonmail.com","SOP67ZVH7RW"),
  ("NSHZFTY064","Flynn Hays","et.arcu@hotmail.couk","NFK71NUF2MR"),
  ("JYSYJMR687","Selma Wong","tincidunt.nunc@protonmail.ca","DNO49QHU6KX");
INSERT INTO Customers (NetID,Name,Email,Password)
VALUES
  ("XSFTCVI572","Rylee Schwartz","ac.mattis.ornare@icloud.couk","FYN54GXB7UL"),
  ("AULNROY137","Bree Henry","elementum.at@icloud.org","JGI55ONQ3EG"),
  ("LKOJDGF387","Stacey Larson","luctus.et@google.couk","BBD11FFK1NH"),
  ("LFCONLT032","Slade Tate","enim@google.com","VKM69NCL9PI"),
  ("JPBCCBK432","Graham Finley","natoque.penatibus@hotmail.com","EEV86DYZ1CE"),
  ("FFIIIOO491","Kuame Merrill","consectetuer.adipiscing.elit@outlook.net","DGJ34UYL1KG"),
  ("RVTRIBJ139","Adria Ortiz","in@yahoo.couk","GYB36UUA1EX"),
  ("LOXIHLJ465","Hamilton Armstrong","congue@icloud.couk","OJU24WBR4FC"),
  ("HMUFFTV117","Kyra Snider","eu.neque@google.edu","QAH33LLT2SQ"),
  ("PDXLWTO837","Lev Dunn","vitae.orci@google.edu","CFX97RND4RR"),
  ("SKDESNB377","Lyle Harris","ultrices.posuere@icloud.com","CZV09LKG4FR"),
  ("HGDBMML299","Matthew Terrell","convallis.dolor@hotmail.org","JPD84VEY7UT"),
  ("JLDPQBY334","Honorato Wheeler","lorem.fringilla@outlook.com","NNB42DSL4YP"),
  ("SMQMFBN831","Vielka Norman","pellentesque.tincidunt@outlook.com","WQY82OAT8JK"),
  ("PTMQWCI453","Valentine Bailey","ullamcorper.velit@icloud.net","EUU16JSM4MC"),
  ("IZCYODL962","Quail Gibson","enim.sit.amet@aol.net","JJL81FDD2PH"),
  ("QPPMZFI222","Nelle Levy","phasellus.nulla@yahoo.com","NXS07LER2RV"),
  ("YGUIIFA245","Rebekah Graham","dui.cum@outlook.ca","NLO81KDN5MR"),
  ("CYEYUEZ817","Adara Bartlett","natoque.penatibus@aol.com","WYP28MQU1CP"),
  ("RFRPGDO118","Castor Talley","sit.amet@yahoo.edu","BQX65SYQ6SY");
INSERT INTO Customers (NetID,Name,Email,Password)
VALUES
  ("EKPRLAF877","Amber Clarke","luctus.vulputate@hotmail.couk","QJF67HVC1QT"),
  ("BARESJW670","Meredith Lowery","ultricies.sem@yahoo.org","KZL32FFP4TC"),
  ("VVBXCKH312","Nora Burns","rutrum@google.net","SLP13KDR3TF"),
  ("ETIZTPG142","Emerson Herring","magna.praesent@yahoo.couk","MQJ48KSR1XA"),
  ("TMTJNYP723","Olympia Ingram","nulla.vulputate@google.org","DPS89KJU2VO"),
  ("IFTWPWE823","Yvonne Burton","nec.cursus@icloud.net","QFP68DXH1AT"),
  ("CACTLQX373","Solomon Rodriguez","parturient@outlook.net","DVQ58CPT3ZH"),
  ("TKXIUAV571","Stewart Cantrell","in.ornare@icloud.org","LJE68VCE3WL"),
  ("UTIHSGW591","Sean David","donec.tincidunt@protonmail.ca","HCR12QVO5JX"),
  ("PWYSQQV284","Gabriel Wade","pharetra.ut@yahoo.ca","EIC81TEH6NV"),
  ("XNCNXSK587","Wanda Combs","phasellus@yahoo.com","YVC17NVO1PU"),
  ("FDLNNHB564","Nadine Ewing","dictum@yahoo.org","KUT01DCO5WL"),
  ("NDGXIQN058","Francis Mcgowan","non@yahoo.org","MWL27BCM9VA"),
  ("GGROTOO623","Lucian Jefferson","a.facilisis@icloud.edu","OHW12XVO7RI"),
  ("XIVYYLO611","Jescie Barr","aenean.sed.pede@outlook.edu","SPI66LCT6QO"),
  ("BPRPPWL123","Scott Dawson","ad@google.edu","UUQ99FRG8BI"),
  ("KYMHSEZ208","Pearl Banks","sed.sapien@protonmail.net","TZE78BGX5MS"),
  ("TANUXUJ838","Ivor Daniel","sed.est@protonmail.net","YFE62QCG5KD"),
  ("GMBDAOZ517","Naomi Merrill","sed.nulla.ante@hotmail.edu","YRR48IYX3RO"),
  ("BAAPHES274","Renee Torres","enim.curabitur.massa@protonmail.org","RJK28LQC0MM");
INSERT INTO Customers (NetID,Name,Email,Password)
VALUES
  ("BJKUEUJ858","Victor Roman","adipiscing@protonmail.couk","JYS75RXP4XQ"),
  ("GJMIJUT361","Desirae Mullins","adipiscing.non@aol.org","RSN14SJS8SC"),
  ("SCJBMIQ926","Tyler Wilder","libero.dui@protonmail.couk","UKO48TIU8HM"),
  ("LBIIILR727","Hunter O'Neill","lobortis.risus.in@hotmail.org","YZA84GXB0VB"),
  ("ZFDVSSQ112","Clare Guzman","justo.faucibus@hotmail.net","EEL52PXQ0GA"),
  ("XVVHJNV757","Thomas Adkins","nibh.quisque@yahoo.ca","PUJ89ORO1WD"),
  ("VHTJJSX409","Lee Bailey","mi.pede.nonummy@yahoo.net","PGX72UVE5FS"),
  ("LBEGBZV606","Uriah Medina","lobortis.mauris.suspendisse@outlook.com","FKU37GEV1XO"),
  ("PXVKJHB961","Oren Mcdowell","neque.pellentesque@google.org","LKP66ACO5AE"),
  ("XQWMYUN666","Roary Mcpherson","felis@protonmail.org","AZG64VYQ3EF");
INSERT INTO Customers (NetID,Name,Email,Password)
VALUES
  ("VXVNMPQ364","Lee Albert","mattis@icloud.ca","YOP05XBK9UE"),
  ("AWGRQOS380","Tamekah Forbes","diam.lorem@google.ca","GLF58XWE5ZC"),
  ("AUGNRLD437","Faith Mcdaniel","enim.curabitur@google.couk","YGP86PGO1UH"),
  ("INWNQVV440","Odessa Black","donec@aol.couk","LIN44IUF6JU"),
  ("GUCYBQT926","Hu Campbell","dolor.tempus.non@icloud.edu","WTL19QYC0OS"),
  ("NDDCAPJ198","Delilah Kelly","a.dui.cras@outlook.net","HVI47ISO0HA"),
  ("UENSPJF536","Virginia Morris","habitant.morbi@protonmail.org","XKK72UPQ0CF"),
  ("BIKWLLV328","Dorian Winters","lobortis.ultrices@yahoo.net","VSZ33QMS1AF"),
  ("XJBJFET683","Moana Nguyen","id@outlook.couk","KUG11HNJ6NN"),
  ("BGXIGWK758","Macy Mccormick","nisi.mauris.nulla@icloud.org","IHI89OFC8BN"),
  ("OQCBQRR622","September Madden","quisque@aol.com","DNJ36KMW7LX"),
  ("VJHZXZT883","Rose Cantrell","ante@hotmail.ca","XDW32TKI8WH"),
  ("LUPQBZK323","Prescott Harrell","dolor.fusce.mi@yahoo.com","WXY62EXK2YB"),
  ("EHXWNMM311","Priscilla Day","non.arcu@yahoo.edu","UYR90DLL3SO"),
  ("RPQIHRM814","Tara Calhoun","amet@icloud.com","OKK60YMX7PE"),
  ("YMGHNGO527","Stella Jordan","nec.malesuada@hotmail.edu","DGV63MQU6NN"),
  ("MXYFNIL471","Driscoll Christian","erat@hotmail.ca","WOV88DVK7GE"),
  ("VERUOKB192","Sydnee Rosario","eleifend@yahoo.edu","BXQ77RBT5EK"),
  ("QHXFQTT685","Elliott Riddle","vitae.nibh@protonmail.edu","RQR87VRP3DW"),
  ("KFJJRQZ518","Zeus Frederick","velit@google.edu","TTW62FYN3ZF");
INSERT INTO Customers (NetID,Name,Email,Password)
VALUES
  ("YGHEJIH716","Norman Hunter","sed@icloud.couk","SLE14YKW7PI"),
  ("CLTRGHK451","Cole Nielsen","nunc.ut@yahoo.edu","VBO64KSV7DB"),
  ("KYJPBQG722","Jarrod Hunt","dictum.mi@google.ca","ESB26EEK7JB"),
  ("QPWKDMT308","Julian Blair","pellentesque.habitant@google.ca","NVZ47SUL2SV"),
  ("LDDVFFQ054","Christian Greene","magna.cras@hotmail.edu","EVE19FPB5DW"),
  ("WJWVUYK163","Hu Bradshaw","eget.metus@hotmail.net","VKF22OMT5NY"),
  ("JCYTSMZ766","Kevin Duffy","vivamus.euismod.urna@icloud.com","QSM68AXR4BA"),
  ("TLINMYT368","Anthony Blackburn","pharetra.nibh.aliquam@yahoo.ca","YMQ54QOQ6BX"),
  ("FGDKCSG781","Ann Russell","vivamus.nibh@icloud.couk","HLX54HOZ5OQ"),
  ("OKYQBLS040","Wendy Mcknight","quis.pede.suspendisse@protonmail.couk","JCG38BFW6LF"),
  ("PONHSXF361","Clark Mayo","mus.proin@hotmail.edu","SUT12BVX4PO"),
  ("ZQIOOEW804","Illana Vaughan","sed.id.risus@hotmail.net","HMW48JAS6EM"),
  ("HDPUNCM972","Lydia Battle","pede.nec.ante@icloud.couk","WIK02AEL0BY"),
  ("WBEKMBT863","Kellie Witt","eu.nibh@aol.couk","VVI44JKC2OI"),
  ("LQHXCPS453","Callie Watts","sed@google.ca","GCY23YLC1LR"),
  ("DWTPIPB118","September Parks","proin.dolor@google.org","PFU17ONY5XU"),
  ("HRTKKUD266","Salvador Pruitt","urna.justo@protonmail.net","EOX84NFP1WR"),
  ("NRFRVTC301","Eleanor Wall","egestas.nunc@hotmail.edu","OEV66BZO8EO"),
  ("GRWJKQF533","Upton Mathews","quam.quis@outlook.com","SXR83UNT3MU"),
  ("XGGNGGN225","Keane Hays","arcu@protonmail.couk","GPS52XTU2HJ");
INSERT INTO Customers (NetID,Name,Email,Password)
VALUES
  ("DTKQKJY423","Martha Morton","eu.dui@google.couk","YWP78NSI8EU"),
  ("IVGPCXL547","Quinn Reilly","magna.suspendisse@outlook.com","FAL06SWQ7XM"),
  ("KYJKLQR547","Winter Townsend","enim.sit.amet@outlook.edu","MLL33RGL1GJ"),
  ("XYHHJPO531","Rowan Fletcher","libero.mauris@icloud.com","RCQ15NMF2II"),
  ("PFSYGJH501","Claire Macdonald","ultrices.mauris@icloud.net","YZN35MWG3YP"),
  ("NKPNEEE391","Kaitlin Knowles","eget.metus.in@icloud.net","LWM57YTY4JJ"),
  ("URNEXWC755","Lavinia Burks","sit.amet.nulla@yahoo.net","BRU33CYB5NV"),
  ("XDJHIKL513","Isabella Lynch","lorem.eget@hotmail.edu","XOZ24XTI8ID"),
  ("GJGYMOY054","Hakeem Sykes","tempus@aol.com","TGH54ADJ6IM"),
  ("WDVYWSG886","Chastity Abbott","ipsum.ac@google.net","QFN13SCL0VM");
INSERT INTO Customers (NetID,Name,Email,Password)
VALUES
  ("KDTTDVG693","Sarah Mccullough","sed.eu@hotmail.net","NXG34DGU7GY"),
  ("BHNHMPH748","Travis Cook","purus.sapien@yahoo.couk","BYX82TKF5VJ"),
  ("HTVODBB738","Phyllis Harvey","vitae@protonmail.ca","PHS80SOC8NI"),
  ("SJLOAMC127","Ifeoma Fowler","tellus@google.net","IPE22LYO2IR"),
  ("QKSEIJP631","Joel England","adipiscing.lobortis@protonmail.org","UML87ZGU9CY"),
  ("MTPEXUQ572","Pascale Gamble","neque.venenatis@hotmail.edu","PJW55MJC3XQ"),
  ("QEOCOQD121","Amy Barry","vivamus.nibh@yahoo.org","QXE63HLI6KF"),
  ("JBIXPOI170","Upton Watts","semper.cursus@aol.org","CIX64ISL7LR"),
  ("WNRCGYK781","Igor Gutierrez","hendrerit@google.ca","THP69PEM5UF"),
  ("BRQSVXY697","Hannah Ayers","lectus.nullam.suscipit@google.com","LJW70MWP5WD"),
  ("KHBIWWV685","Quail Trujillo","sit.amet.consectetuer@aol.edu","KAY57SDO4CP"),
  ("SUKXQRF264","Kiara Mccall","odio.nam@outlook.org","OWJ31WWQ5AT"),
  ("DQJIIJL132","Sybil May","aliquam@yahoo.com","ZGL16USY5DX"),
  ("PLYCSSZ232","Leroy Bruce","per.conubia@icloud.net","EFZ52EDT5BJ"),
  ("XJNLRDR376","Chaney Marquez","suspendisse.non@yahoo.org","ZMC45SUY0GR"),
  ("JBIMTLD536","Ocean Kirby","sapien@protonmail.ca","MZH43FQH9SG"),
  ("CLPVWJB408","Wynne Cash","felis.orci@outlook.ca","YSU96HWB3DY"),
  ("ZGAILMZ193","Logan Gallegos","aliquet@google.com","XKR38ULF3ZV"),
  ("ICIQEWX793","Richard Ayers","purus.duis@hotmail.edu","RRG74JUL5GD"),
  ("SFSBLMU435","Jermaine Greer","est.congue@outlook.org","OLK26WER6PD");
INSERT INTO Customers (NetID,Name,Email,Password)
VALUES
  ("FGWYQMU637","Roary Ball","vulputate@icloud.couk","TFT36IYX8DG"),
  ("RPSRHUM442","Wallace Reynolds","quam@aol.net","OCI93QFN3VV"),
  ("UDJELMU723","Stella Mitchell","sodales@outlook.edu","XIL87YKG0KD"),
  ("SSNEUIC912","MacKenzie Bowen","metus.vivamus.euismod@yahoo.ca","ZVF07CFY4XI"),
  ("RLZEFHF476","Jesse Thomas","diam.vel@yahoo.ca","YEO49XFG7LW"),
  ("WACUWSF361","Sean Harrington","erat@hotmail.ca","JBB93MLN6PP"),
  ("RMHUPRQ280","Justin Malone","suspendisse.tristique.neque@hotmail.com","BZZ17UKS2TU"),
  ("VMHOMSE179","Omar Maldonado","quis.urna@outlook.com","XCX38HHL6RL"),
  ("FBEYLWI211","Gay Hall","turpis@icloud.ca","WMB35XWH3VJ"),
  ("EFXELRD638","Zena Baldwin","molestie.tortor@yahoo.ca","QKD38FBG6EN"),
  ("UFPPSNO675","Elijah Beck","aliquet.vel.vulputate@icloud.org","HMI05TSZ6MH"),
  ("FGUIKLH474","Quintessa Sherman","nunc.nulla.vulputate@icloud.edu","HME82EYW3QR"),
  ("QJDJNOX859","Gail Mack","volutpat.nunc@google.com","KRK94DRW9SA"),
  ("OEDRKUM127","Owen Peters","nibh.aliquam@yahoo.org","JUL76HFG6WP"),
  ("FVTCXUW216","Ella Martin","cras@icloud.net","DEJ26YQG3YK"),
  ("CNHHHDY331","Brenda Bradford","sodales.purus@aol.couk","JYT48WKW1ER"),
  ("EUVMEEU318","Celeste Pacheco","non.arcu@hotmail.com","KSA46FKW6XV"),
  ("UYMSXRI826","Riley Johnson","congue.in@google.org","XRU34WGN3NM"),
  ("GCNDUGN141","Bevis Francis","sed.congue@yahoo.couk","ELS25ULR8DQ"),
  ("ISJTWME831","Joel Fitzgerald","dolor@yahoo.couk","QYB91BRA7JV");
INSERT INTO Customers (NetID,Name,Email,Password)
VALUES
  ("UASKWWB761","Wade Manning","rutrum@protonmail.com","BJE37WWM6TA"),
  ("VEACGAT766","Karina Oneal","tellus.non@google.com","QRM76TVC6OL"),
  ("NFPVXIX755","Ocean Navarro","euismod.et@yahoo.couk","KXD39BGL8SB"),
  ("QHGNRKN576","Raymond Oneal","metus.aliquam.erat@aol.couk","SBB96JEP1VW"),
  ("GIZXSGM745","Shelly Forbes","bibendum@yahoo.edu","UFY31LMQ5BY"),
  ("MIQPINF669","Lamar Wiggins","vehicula@protonmail.edu","PNR06URF0YP"),
  ("HVABFMV617","Quinn Gregory","fringilla@yahoo.edu","FXR77IUW2OF"),
  ("MKCXTNF414","Lawrence Rosario","aliquet@protonmail.org","PEI21LYD2TI"),
  ("MGBKGVJ024","Samson Russell","tristique.pellentesque@outlook.ca","QKK55UPJ7EE"),
  ("CWVKOUR373","Jane Webster","fringilla.euismod@hotmail.net","JMD31ENN7IP");
INSERT INTO Customers (NetID,Name,Email,Password)
VALUES
  ("KOWDBGH448","Lucius Webb","aenean@icloud.org","FYU95PHO3TF"),
  ("NWSXCEO674","Kiayada Holmes","eget@yahoo.couk","RJA39FPD5NB"),
  ("GFWQOPG268","Elijah Kent","tellus.suspendisse@yahoo.org","YBL75WUU4YS"),
  ("VEDZLRY763","Erasmus Rios","in.molestie@yahoo.net","JSO75ZBU8LF"),
  ("XZOZFCM102","Ivana Jones","tincidunt.nunc.ac@hotmail.net","VMY57MXN2YK"),
  ("YUSKSRV420","Madaline Fitzpatrick","erat.vivamus@yahoo.ca","ADC65YKZ0FC"),
  ("PFCSSFL848","Kirk Avila","sem.elit@hotmail.couk","LHG19SGR8AQ"),
  ("PFHRUUW648","Irma Page","a.neque@icloud.couk","FQB39QCI1GV"),
  ("WPLSDYR547","Mannix Good","nullam.enim@protonmail.org","HJG25IKF5TA"),
  ("IKHRRHS577","Gisela Hernandez","nullam@hotmail.ca","LAO45FQJ3GM"),
  ("IIOEEPR044","Chandler Gaines","cras.dictum@google.org","THH60IVK2LC"),
  ("AQQKRBM544","Alfonso Newton","metus.urna@protonmail.edu","IUB26IBP5LL"),
  ("CCMDKIO652","Jennifer Kramer","luctus@google.com","DBX11WJF5LM"),
  ("QCHZOID319","Donovan Hawkins","feugiat.lorem.ipsum@icloud.org","DSJ19QZG3JE"),
  ("OYCIQIQ079","Sawyer Stokes","nec.quam@google.ca","PXM74PKO4IE"),
  ("SGAVIUL381","Jonas Reese","a.felis@google.edu","JTW68RWO0JL"),
  ("NENOAZD755","Preston Yates","id.nunc@aol.org","HRT26MRW5TC"),
  ("OTWFNYA878","Stewart Perez","magna.tellus@outlook.edu","QFY62SMG3VW"),
  ("MDXLCSW819","Nathan Morin","vestibulum.ante@aol.edu","FRA59QJU1FJ"),
  ("BXQUGMJ512","Martina Adkins","rutrum.eu.ultrices@hotmail.net","UNW67FYJ6XR");
INSERT INTO Customers (NetID,Name,Email,Password)
VALUES
  ("RSGPXWZ951","Wynter Edwards","amet.ante@yahoo.edu","CKH54GSW5ZF"),
  ("PABDEQY111","Ciaran Lamb","amet.massa@hotmail.couk","MYI33FUK8JG"),
  ("CMOFEHZ357","Ignatius Bray","interdum@hotmail.com","YHT07RQZ7MV"),
  ("PQXOZMQ678","Isaiah Buckner","magna@hotmail.edu","QZD39CLF6OD"),
  ("HNSYCSV658","Veronica Cameron","volutpat@icloud.net","QPY36LPD4SO"),
  ("QJJULEJ857","Levi Jacobson","urna.suscipit@yahoo.edu","JML98WXQ3PC"),
  ("QPWFGOD001","Orla Heath","phasellus.vitae.mauris@protonmail.couk","MEV25DWU0QG"),
  ("JJEQHGH512","Mohammad Walters","ullamcorper.eu.euismod@hotmail.edu","VEL37HRR5XW"),
  ("KOPOCTB516","Yuli Hopper","convallis.dolor@yahoo.com","VUI55ITJ6UL"),
  ("FVGYNHG560","Brock Reeves","imperdiet.nec@icloud.net","CCS17UTH7GF"),
  ("WYUYSIX111","Zeus Rush","eu.placerat@icloud.edu","ZJS87ZFX7QC"),
  ("ERGGIIL988","Zahir Dawson","cubilia.curae@protonmail.ca","UOS83IIS1VC"),
  ("WZCTRYL503","Megan Dalton","senectus@icloud.com","HOW82FSV7QZ"),
  ("PIXQXPI596","Adam Olson","aliquet@hotmail.edu","GOV41SQS4IQ"),
  ("ODBOXXD067","Hop Kennedy","mauris.sagittis@google.ca","HFP07CYX4QB"),
  ("RXMDVYL194","Brendan Guzman","in.sodales.elit@protonmail.net","WFH16SFL4EI"),
  ("TERBLHV587","Sebastian Knapp","arcu@aol.edu","BPF25MGH0FB"),
  ("PMKUDGI341","Emi Willis","eget.volutpat.ornare@hotmail.couk","QJW31ZSH3FQ"),
  ("KPTMYGY633","Castor Mccray","feugiat.non.lobortis@icloud.ca","GSF38BMA1IN"),
  ("XSIDSKR624","Ivory Garcia","metus@google.couk","QNM19UDM5UC");
INSERT INTO Customers (NetID,Name,Email,Password)
VALUES
  ("SIDDVLX982","Martin Benton","vel.quam@outlook.couk","IOS81JLY0MT"),
  ("MFJUTBI883","Anika Leach","in.mi.pede@hotmail.couk","NND34EXL5OO"),
  ("TQIQBEO248","Hyacinth Sears","tempus@hotmail.ca","MCX42MDF1QN"),
  ("YGTVXFD625","Jaquelyn Maynard","nec.tellus@protonmail.couk","HWV61EYF7XD"),
  ("WICSDQG627","Ronan Mitchell","sit@yahoo.edu","BUH71MPW6HT"),
  ("QRSYAZG485","Scott Rosales","mauris.nulla@yahoo.org","BQI36FQE3MY"),
  ("FLCMONI931","Idona Reed","interdum.nunc@aol.net","DTN94JUP6MS"),
  ("DDLOTUN639","Silas Booker","sodales.mauris@hotmail.net","JQR81KQI4VO"),
  ("LIWCVVJ973","Conan Lara","ipsum.ac.mi@protonmail.com","DCF54OLV4AV"),
  ("QSYJKWN826","Conan Richards","eget.metus@icloud.com","DWU21AVF5HE");
INSERT INTO Customers (NetID,Name,Email,Password)
VALUES
  ("VQXYWJZ746","Michael Puckett","dolor.quam.elementum@outlook.couk","PNE25NDR8ZY"),
  ("UUHRQPD225","Sean Rowe","curabitur.egestas@protonmail.org","LUK77GWI6HJ"),
  ("WBWNIBA612","Ethan Kelley","gravida.praesent@google.couk","EYB66ESW6DN"),
  ("WJHGNSP817","Rhona Odom","sit.amet.lorem@icloud.edu","ECC27NMN3ZR"),
  ("RDHUUPU415","Jermaine Bentley","interdum.sed.auctor@hotmail.edu","VCT25QIX1XU"),
  ("KBWEDMY222","Aquila Greene","ligula.elit@hotmail.ca","TSJ26RQO3DQ"),
  ("QVPHNMM841","Gavin Carey","ante@google.edu","DOJ62OGQ4JX"),
  ("UCSTCEG377","Nissim Levine","in.at@hotmail.ca","BCK75YNC9JH"),
  ("AOYXGNW438","Tara Reese","ante@icloud.com","DSO39RAH5JW"),
  ("PKULPVJ509","Vernon Mosley","varius.nam.porttitor@yahoo.net","QSF03MJU4IO"),
  ("IHTTHNK033","Jamalia Hutchinson","egestas.a@icloud.edu","NIR74OES2NM"),
  ("QNBDVEP618","Harrison Marshall","lobortis.risus@hotmail.org","PSG51NSC6US"),
  ("ISPOGTL236","Gary Horton","tempor.arcu@icloud.couk","TEB50FLS2IF"),
  ("HKKUVAZ360","Drew Price","suscipit@icloud.net","LPO95NBB1TJ"),
  ("RJKUPIW556","Willow Miller","curae@protonmail.edu","DDV27BRF7SD"),
  ("RCVITJH299","Declan Holder","non.hendrerit@aol.com","VFI33KWV8HS"),
  ("QJSPFED251","Alfonso Andrews","suspendisse@hotmail.edu","EOW16EIV3LQ"),
  ("BKACRLE534","Garth Mckay","suspendisse.aliquet@outlook.com","EOG72PIW4TI"),
  ("FYNQOSP642","Barry Hester","amet.consectetuer@protonmail.ca","STE56XNN2LR"),
  ("HNLYPWU081","Hollee Gardner","est.tempor@yahoo.ca","ARJ21LUR9CH");
INSERT INTO Customers (NetID,Name,Email,Password)
VALUES
  ("AXOQIOW137","Kennan Duran","fringilla.euismod@icloud.ca","WAS94OKA8UJ"),
  ("PCCOIUD746","Darrel Elliott","amet.dapibus@aol.org","DWR51ZLI4YG"),
  ("VZMKYIS414","Sade Hardin","maecenas@google.edu","OQS16HEY2CC"),
  ("ZUQYJID516","Cruz Vincent","nulla.facilisis@icloud.couk","SHH23SJX2IQ"),
  ("MUDNFYO319","Cyrus Hampton","porttitor.interdum.sed@yahoo.couk","CPF53KLW1OM"),
  ("FBIDBYG603","Daria Ware","ipsum.dolor.sit@hotmail.com","RMF30YDO3CE"),
  ("HMZLUMM418","Myra Mendoza","praesent@aol.org","ECP22JWZ6UD"),
  ("FOBLIOI936","Calvin Caldwell","eros@aol.org","XLJ80FNM3JQ"),
  ("PWOKMKL754","Farrah Estes","ipsum.sodales@icloud.net","TDQ29EWX6MH"),
  ("KSFNCXU172","Mira Carr","imperdiet.ornare@outlook.net","CDK46YSR9UJ"),
  ("ZSIJGNT696","Debra Spence","phasellus.fermentum@aol.couk","JMK85FJE5DF"),
  ("MJEBADS117","Noble Durham","magnis.dis@icloud.edu","GID58TOU7MJ"),
  ("KKDSTKQ242","Jaime Rodgers","consequat.purus@icloud.edu","YXH36VRU0GL"),
  ("GSBVDCF764","Cally Shaffer","felis.purus@aol.couk","UWR78DLG1UP"),
  ("ABMQOPU945","Anthony Campos","mauris.non@protonmail.ca","KUQ47PPQ8CY"),
  ("ETPSQQU402","Ira Spears","vulputate.dui@yahoo.ca","NFV14DIM2QO"),
  ("YEFHSJJ996","Germane Fischer","vitae.sodales@google.couk","CPD67ONU7MN"),
  ("UDDSOSS504","Petra Charles","tellus.faucibus@protonmail.net","QYH64BPZ6MI"),
  ("YPJRMSD148","Chaney Rodriquez","laoreet.posuere@google.org","YBZ70OYY4XT"),
  ("PBKSZXM805","Russell Rios","sed@hotmail.edu","ZTD17MGB6KG");
INSERT INTO Customers (NetID,Name,Email,Password)
VALUES
  ("LKQJCLM127","Rae Holden","dui.lectus@icloud.couk","FPN48HMW8KS"),
  ("WIFIFRD446","Sawyer Ramos","augue.eu.tempor@outlook.org","OHD14LEY3YZ"),
  ("QCHNCSO283","Brittany Pierce","sed.orci@google.couk","QMC90SGS5LX"),
  ("OGJMHXX627","Winter Trevino","lacinia.orci@icloud.org","QMC48CBL3ER"),
  ("SOWDSQW244","Owen Puckett","aliquet.libero@protonmail.couk","HTG58ENJ3NY"),
  ("WVMTZCB242","Clarke Pace","sagittis.placerat@protonmail.org","WXR72AYV5TC"),
  ("ZMQOIOR973","Ila Stafford","molestie.tellus.aenean@yahoo.edu","SRU32LZO6JV"),
  ("KPOHKTB341","Bradley Fitzpatrick","neque.in@yahoo.edu","YMO18FHY2AN"),
  ("NITVESR576","Kylie Jackson","non.nisi@aol.couk","CGA76RHL3JG"),
  ("GEDXSOT226","May Phillips","dui.augue@icloud.net","YXM28RUG8ZA");
INSERT INTO Customers (NetID,Name,Email,Password)
VALUES
  ("YYZTGYL379","Christopher Solis","pellentesque.ultricies@hotmail.org","DSI51LOL6ID"),
  ("WNODUDW768","Delilah Mejia","quis@yahoo.org","PIR62QOY0LZ"),
  ("DWVFODH698","Aurelia Dillard","sagittis.nullam@google.org","RNJ98QRX4VT"),
  ("FERDCMN167","Elvis Morrow","massa.suspendisse.eleifend@hotmail.couk","UMR55SBP1MG"),
  ("AEOYGYC054","Thor Tucker","conubia.nostra@protonmail.com","YZG35BUI6CT"),
  ("GJILBFL646","Eagan Miller","pede.malesuada@aol.ca","XEN84TMQ7FR"),
  ("FKCNNCE142","Guy Kane","turpis@icloud.couk","ZUP73QQH8XL"),
  ("ESXMPSR042","Fatima Massey","ut.pharetra@outlook.ca","JTQ75RFQ7DO"),
  ("XNRJTYO106","Ishmael Kerr","netus.et@google.ca","MLH74VKO4MC"),
  ("SGXIKCD615","Hoyt Mcconnell","consequat.dolor@icloud.com","GGY71LQN0CK"),
  ("YDPPTYR517","Ivory Clark","malesuada@hotmail.org","UDO55PEC2CI"),
  ("EUTNSTH351","Francis Potter","purus.ac@yahoo.edu","WHY48PLZ4OP"),
  ("KBCPLIX481","Cora Cote","faucibus.ut@icloud.ca","YDZ33OQF3NH"),
  ("MIQIEWX858","Aurelia Jackson","consequat.auctor.nunc@icloud.org","FGC69SJG4MH"),
  ("NICCWGR150","Murphy Conner","porttitor.interdum.sed@hotmail.ca","IKB16RTN6BR"),
  ("DPMLYCZ655","Roanna Moreno","et@icloud.com","GNF56YUN9PT"),
  ("MCVKPSU716","Lucian Delaney","urna.suscipit.nonummy@google.com","DCL23RNC2JI"),
  ("HLMSPEZ644","Ursa Haynes","eu.euismod.ac@yahoo.couk","UQU12LSB0JZ"),
  ("LMHVJNE412","Todd Kirk","rutrum@yahoo.edu","ACC77NPU1HK"),
  ("FVFUWQH585","Quinn Mccarty","nisi@google.com","VLL53RUD4OC");
INSERT INTO Customers (NetID,Name,Email,Password)
VALUES
  ("HSMSINW284","Carlos Hull","in@aol.net","TII71SSS0CK"),
  ("DUKUMGJ791","Karly Jennings","eleifend.nec.malesuada@protonmail.ca","LWE57CRO5OC"),
  ("IFQOLJO048","Chelsea Atkinson","aliquam@yahoo.couk","GUB11OKT1OO"),
  ("WUIMANC831","Cullen Burton","nulla.dignissim.maecenas@outlook.com","NSY12EIG1DW"),
  ("INSHOZK236","Bethany Young","eu.tellus@protonmail.couk","PQD51EIN1EM"),
  ("MYBKYGY676","Damian Barker","proin.non@protonmail.couk","DFP21KSR6LA"),
  ("PAWLZYV477","Violet Fisher","at.iaculis@google.com","EDA82ZDP7NQ"),
  ("IUOCCHU521","Damian Compton","libero.at.auctor@google.net","GST58EIY1RY"),
  ("PTADFYH327","Andrew Porter","at@outlook.org","HGG86FTU4IQ"),
  ("ULKMXNJ186","Upton Battle","tempor.est@hotmail.edu","GXL51LGX4BM"),
  ("ZLNLQQD774","Peter Huber","commodo@yahoo.couk","JTI48JWC5CF"),
  ("HHSBCRM181","Beck Wade","eget.magna@icloud.org","IRU38PLT3HZ"),
  ("PMMLPEI154","Jocelyn Barber","lectus@protonmail.edu","KGM55CKF4LL"),
  ("VNMMJIX441","Yeo Cabrera","feugiat@icloud.net","OWE65HXV2RX"),
  ("DLOMUVR345","Myra Cox","tellus.sem@yahoo.edu","MUZ68LIF2GS"),
  ("KQJUDBJ582","Graiden Knox","neque.nullam@google.ca","ORV04FNN3MX"),
  ("WRJNCAH578","Ivan Bentley","mauris.morbi@icloud.edu","TEB16HHY6YB"),
  ("NWKSVRY446","Felicia Mays","convallis@google.edu","SOM41KFJ1CC"),
  ("QINKDSY347","Lane Mayer","tempor.diam.dictum@icloud.edu","CTR52ALU7BP"),
  ("PDSWFMC844","Hector Alston","enim@google.com","PMZ53GHJ5SL");
INSERT INTO Customers (NetID,Name,Email,Password)
VALUES
  ("IEFVYEQ606","Unity Carson","mi.ac@protonmail.edu","ERV67LLT1FH"),
  ("JUTLHKK547","Joelle Kelley","netus@hotmail.edu","QLD90DNT3DO"),
  ("JGQLWPU043","Colin Sosa","vitae.aliquam@protonmail.org","NJC21SIT3VQ"),
  ("HMFWHSF250","Lunea Mays","rhoncus.donec@google.com","ASG86QKK1QE"),
  ("RGNJXGD806","Driscoll Bernard","nibh.donec.est@protonmail.com","EKC69JNX4DI"),
  ("QNVTMEJ959","Thomas Ashley","magna@aol.com","TIK44UOI3FA"),
  ("TGQFREG522","Gisela Davis","ipsum.phasellus@icloud.net","YIH76OXF1LL"),
  ("HZKOTIW323","Tyler Gould","dui.fusce.diam@icloud.net","WIY23DWF7TM"),
  ("HALMMBR016","Cairo Barnes","laoreet.posuere.enim@protonmail.com","JVG39XFG9OH"),
  ("OSSSQEW189","Hall Short","feugiat.placerat@protonmail.edu","JMA14QRI3TM");
INSERT INTO Customers (NetID,Name,Email,Password)
VALUES
  ("YTSTBPQ304","Malik Gamble","tellus.sem.mollis@yahoo.com","RLE21GUD6IW"),
  ("HMXWHIO648","Myles Guthrie","a@outlook.org","OTK46IUR2SO"),
  ("LCOSDFZ081","Ima Mathews","elit.pellentesque@icloud.couk","EBM37OSR8XK"),
  ("NESVKPS965","Leigh Molina","magna@hotmail.org","WQG68XFS3LZ"),
  ("AKZGGGC440","Geoffrey Meadows","class.aptent.taciti@outlook.ca","OGX32WUN3NG"),
  ("NLTMCEZ566","Quemby Jenkins","commodo@outlook.com","KVI66JPV2BO"),
  ("ETZGLGT876","Amal Nixon","tristique@protonmail.com","NYB15IOP1UC"),
  ("QZEPRDQ184","Kim Castaneda","hendrerit.donec@protonmail.edu","UVS10TTT2OD"),
  ("DOPJZYH164","Thor Olsen","eget.venenatis@outlook.org","YQF01OXE6UJ"),
  ("ELBGJLY893","Kaseem Mcclure","pede@protonmail.com","ODL61ILB2GQ"),
  ("IBITIFV984","Joelle Petersen","aliquet@yahoo.com","HOY11MTM0QM"),
  ("IRICEWP433","Lara Madden","fusce.mi@icloud.org","PNJ99PPH7PG"),
  ("JUNEEBS305","Ivory Levy","massa.lobortis@outlook.org","DRZ43IMI7AB"),
  ("KRSLGMV129","Riley Johnston","nam@hotmail.couk","MFT70TGK7VQ"),
  ("MDHPZRZ776","Jolene Reeves","molestie@hotmail.net","ZOL33QXW7OP"),
  ("VPFYRZU628","Rowan Buck","donec.non@protonmail.org","ZJO40HEB7BG"),
  ("PARNKUC763","Hilary Wiley","nec.ante.maecenas@hotmail.com","WRN26VHE5KE"),
  ("UFYSEHP607","Aphrodite Hernandez","cras@hotmail.ca","POX42RDZ8JM"),
  ("GEHIUYQ377","Hamilton Roy","vivamus.nibh.dolor@yahoo.net","YRC04KDF1IZ"),
  ("QARYGJB651","Stuart Olsen","cursus@google.couk","GEW64FZS2QR");
INSERT INTO Customers (NetID,Name,Email,Password)
VALUES
  ("MHUCWGN576","Ila Sims","lorem.luctus.ut@hotmail.ca","BCM45HBW1NX"),
  ("BLNMTOQ426","Kellie Hansen","nunc.mauris.morbi@icloud.couk","KQS86UJQ1NO"),
  ("FUINIED245","Cathleen Mathews","semper.auctor.mauris@outlook.com","TUQ77ULU3US"),
  ("JBQZMLR124","Hammett Bishop","mauris.elit.dictum@protonmail.net","SRT17LQK8LD"),
  ("HXZAYZI003","Iola Long","lacus.pede@aol.ca","UCH52WEI2KG"),
  ("KBXKGPR952","Zane Mckenzie","montes.nascetur.ridiculus@icloud.ca","YKQ17KIR5EH"),
  ("RVDYITX302","Candice Arnold","at.auctor@hotmail.org","UTY01CLY4SB"),
  ("IEKRCVG846","Jordan Becker","dictum.eu@hotmail.ca","KND53RCR4BE"),
  ("EVCHFGM820","Hasad Kirkland","porttitor.tellus.non@outlook.edu","AAW49FHN2XV"),
  ("DBYXBJN643","India Rhodes","risus.odio.auctor@icloud.com","MBG86CMV4EQ"),
  ("OPNQGYM638","Jemima Puckett","nunc.quisque@google.ca","DRU87XMQ4HL"),
  ("QNQCVUL946","Akeem Mathis","integer.vulputate.risus@google.net","WRI37YYB4IT"),
  ("UHNVTVV127","Fuller Jordan","mi.pede@yahoo.edu","NFW43LGL3HX"),
  ("XNYJVWP496","Kadeem Greene","etiam.vestibulum@icloud.couk","BQJ71BCS8FZ"),
  ("AOISTPN187","Maite Stanley","libero.morbi@hotmail.couk","FLP88HHK6KS"),
  ("QSHEWFM922","Rebecca Herman","non.lacinia.at@icloud.couk","CEI01TJZ4KP"),
  ("CKMMLBR517","Stuart Vinson","nulla.ante.iaculis@protonmail.ca","DYM93KEU5QT"),
  ("GBRGVVD679","Yardley Salinas","mi@protonmail.ca","NIH56INI4TJ"),
  ("IIUHUWN412","Dai Stark","convallis.est@protonmail.com","LFR82MXQ9UI"),
  ("GRNVSFL224","Scarlett Wyatt","a.feugiat@aol.couk","CSI62FNH7HI");
INSERT INTO Customers (NetID,Name,Email,Password)
VALUES
  ("YKNSTUK432","Rafael Suarez","eu.ligula@icloud.org","PHX40XVM1DE"),
  ("FNFKOGB698","Branden Owens","dolor.tempus@aol.edu","JFJ13PCK5WL"),
  ("YJUWRUU138","Yardley Delacruz","id.enim@outlook.ca","RWH79MUZ6EE"),
  ("PNFPYON618","Jonas Oneil","consequat@google.org","MLX37TOE2NZ"),
  ("VKKMCEO394","Frances Velez","posuere.cubilia.curae@protonmail.org","PQA30VUK2RB"),
  ("UDMKNRU616","Colt Tyler","diam.luctus@google.edu","TSY44WKY2BF"),
  ("QRNZIWB361","Emmanuel Ochoa","tristique.pharetra@protonmail.com","PFB34WOZ8CV"),
  ("SYFDLIL947","Reese Solis","nec.eleifend.non@google.com","CND18YMX5PH"),
  ("STEJVRK367","Fritz Carson","lorem.eget.mollis@aol.edu","MBV94UFC5QU"),
  ("QGCYODX566","Lionel Parks","at.fringilla@outlook.couk","GMF74PQF1PF");
INSERT INTO Customers (NetID,Name,Email,Password)
VALUES
  ("VOUGDYP076","Craig Sawyer","nec.luctus@outlook.couk","HMP41PSY8SU"),
  ("LXBOQTX726","Ezra Bonner","urna.justo.faucibus@outlook.couk","MYN44VEM9JW"),
  ("DSSDDLX431","Sylvester Richard","tellus@protonmail.org","WXF54HEN8EP"),
  ("FWSESZB508","Imogene Gross","a@google.com","JVJ22TFE0AU"),
  ("MNUVCSR621","Imelda Vaughn","bibendum.donec.felis@icloud.edu","FWR19LIL4HE"),
  ("CDGBTTI180","Yen Jacobs","vel.vulputate@aol.edu","TIS08SWO1IR"),
  ("UYCEKCY872","Marshall Boyle","nullam@icloud.com","HLF93CTK2WD"),
  ("IVCDLWI182","Avram Campos","aliquam.arcu@google.edu","KYS36HAS1LU"),
  ("OHGKNIX085","John Koch","a@protonmail.com","YGD53FRI1AM"),
  ("GTSPWND193","Ayanna Rowe","blandit@protonmail.ca","JSK62FHL3YR"),
  ("KBRSNSZ833","Lacey Atkins","amet@yahoo.net","RJX24LGC1XV"),
  ("YLXSZDQ621","Inga Holloway","nullam@aol.org","GJL53QUQ7PK"),
  ("ESBNWYQ222","Brynn Walsh","ac.metus@outlook.ca","LPW60HJZ0SE"),
  ("FBYHYUP104","Vance Nelson","amet@outlook.edu","BVU57RWG8AW"),
  ("ZQTBZSG782","Flynn Larsen","purus.nullam@aol.org","ATM32LQY4SH"),
  ("HNVUANH436","Alea Gonzales","donec.egestas@yahoo.edu","CPR87OLE1XJ"),
  ("TPWVEWU228","Charde Cooley","ac@aol.edu","MQC74CFR2YN"),
  ("EWOPJVY546","Len Osborn","quam.elementum@yahoo.ca","MWU35XZB2TF"),
  ("UGEACFB538","Zorita Tate","consectetuer.rhoncus@outlook.com","LVP59EEM8CD"),
  ("HGLIKPY654","Rhoda Duke","diam@outlook.org","YTY54EVS7TC");
INSERT INTO Customers (NetID,Name,Email,Password)
VALUES
  ("UMPZVJD277","Peter Kemp","elit.sed.consequat@yahoo.org","JFO23FDE4YX"),
  ("YGFVXSA115","Bianca Hudson","fusce.fermentum@yahoo.edu","JVD58IUH3CF"),
  ("GGIATEX162","Carlos Sullivan","magna.sed@aol.edu","OHQ64LBI4VY"),
  ("QWHMJRS372","Abigail Olson","phasellus.elit@outlook.net","IDV37CYI3HT"),
  ("CWTXONK342","Graham Jenkins","at@aol.couk","RIL41QZF3QC"),
  ("ZPCHROX345","Lacey Ford","libero.proin.mi@google.couk","BYF43CWK0BS"),
  ("FKJCNGG363","Courtney Burnett","nec@outlook.ca","TSI54BUY2CS"),
  ("CNHAUSY528","Dahlia Mullen","etiam.laoreet@icloud.couk","MRC22FYH4FY"),
  ("FWQLEWK243","Jackson Munoz","at.risus@outlook.ca","CEU15NEN6PC"),
  ("FASVBIF841","Ray Bradley","laoreet@outlook.org","ONZ55YII8JP"),
  ("YDGOWLS611","Grant Cross","blandit@aol.com","SSG34SGR6QA"),
  ("VYGHTUR352","Lev Allison","ac.ipsum.phasellus@outlook.ca","ZOY16KTU1RO"),
  ("WAJUUYD277","Peter Haynes","ligula.aenean@hotmail.couk","QHE54WGE8KI"),
  ("RWMHPIC265","Sheila Combs","dapibus@icloud.com","ZQU37TVQ8JX"),
  ("SPZWDWX894","Quail Roman","enim@yahoo.net","LXE15PJN5IG"),
  ("FLCQPJF739","Macon Parsons","nisi.magna@icloud.ca","HAM34DJR7XU"),
  ("AAYVEKV856","Ann Salinas","ac.nulla.in@protonmail.org","YMW45WCV5PF"),
  ("WFKXTBO167","Desiree White","orci.tincidunt@icloud.couk","WTU26QBO8PE"),
  ("XARTKGV054","Emmanuel Summers","ac.mi.eleifend@outlook.couk","ODE57XIU3BE"),
  ("HSYJBOM406","Blythe Mayo","neque.et@hotmail.org","BFY73CHP4UT");
INSERT INTO Customers (NetID,Name,Email,Password)
VALUES
  ("CEKCOYD667","Tucker Bass","consequat.enim@icloud.couk","CCA78ODT2QW"),
  ("LWNBUXV827","Grady Aguilar","nostra.per@google.ca","KQX21XQW6JQ"),
  ("MTJBIHV059","Breanna Watkins","facilisis.facilisis@google.com","FDY60RBQ6UT"),
  ("UROIPVU422","Reagan Rice","sodales.at.velit@outlook.org","HYS78HMN6DY"),
  ("VPBPOXY045","Willow Nunez","molestie.orci@aol.net","BLS32VIC7CZ"),
  ("PSVYWRM362","Brady Decker","id@protonmail.org","SFO43FGN1NC"),
  ("IFCZNUT703","Vielka Barrera","nec.ante@hotmail.edu","GEF31QJN7IG"),
  ("CLQFXBF522","Tad Todd","non.arcu@icloud.org","JHV35ODU9WE"),
  ("KHVIKSE759","Reagan Sosa","et.ultrices.posuere@hotmail.com","VRC08XBZ3VI"),
  ("VRMXHQE948","Duncan Allen","et.pede.nunc@aol.com","KYO59SSR8ON");
INSERT INTO Customers (NetID,Name,Email,Password)
VALUES
  ("SUTKZHL138","Fritz Lucas","duis.elementum@google.ca","OJQ60EMR4QN"),
  ("ORJFIRJ544","Katelyn Simmons","vulputate.mauris@protonmail.ca","ZRE38NVZ2RL"),
  ("DDVNVDV246","Ginger Kemp","nec.cursus@yahoo.org","KVQ32KIT4PN"),
  ("XGXMHKV073","Latifah Holden","diam.lorem@outlook.org","GUI02ZII9MA"),
  ("YICVQZY647","Kaye Greene","congue.turpis@outlook.org","IYT82KGU1KV"),
  ("BXLMIYC516","Brennan Doyle","lobortis@hotmail.net","YLC47NKF7DD"),
  ("XJOHOOJ350","Indira Hayes","non.vestibulum@aol.com","BRE76JPN2XN"),
  ("DOTKQIL152","Cyrus Le","tellus.justo@icloud.org","OBY23FTT3UO"),
  ("CXHUFOS641","Lillian Black","felis@protonmail.net","PTR43SIO3BT"),
  ("IFWIVOF359","Daniel Campbell","tempor.augue@yahoo.ca","XFL79BJB6IO"),
  ("SSTGHKM632","Cherokee Conley","sed.tortor@protonmail.ca","QPA68EHW1WO"),
  ("GFWQRRS357","Jesse Everett","varius.et@protonmail.edu","JKN17LER1PF"),
  ("CKIWOXE884","Bruce Alvarado","quis.diam@aol.ca","NCQ58PNC0RI"),
  ("MJPUDMO196","Melissa Shaw","risus.quisque.libero@icloud.org","KSB42JLN1SY"),
  ("UUANVON142","Hu Dillard","felis.orci@protonmail.edu","IMM80NDA1EO"),
  ("PSHKJIU240","Felicia Wilder","non.lobortis.quis@aol.org","BDQ93IDQ2TY"),
  ("XDKWIXN152","Kasimir Hines","amet.risus.donec@google.edu","NEL22XWW4MX"),
  ("BMHKFFX082","Kameko Calderon","velit.justo@outlook.ca","HZV54MQU2PL"),
  ("FWCYRNF908","Upton Gallagher","lorem.ipsum@icloud.couk","CEG14MTN0YF"),
  ("HWQRMIA529","Nevada Leach","cursus.integer.mollis@icloud.ca","KCR08YBI2HY");
INSERT INTO Customers (NetID,Name,Email,Password)
VALUES
  ("GSKIMSM014","Katelyn Dale","donec.egestas.duis@aol.net","PNM83RCG6SG"),
  ("DOGPQBU224","Winter Haley","netus.et@aol.ca","VBY97LNM3FN"),
  ("DPUBFVR827","Eugenia Ortiz","at.lacus.quisque@hotmail.org","ZAV98OLO9XB"),
  ("YKMYRLE414","Orlando Church","ante@icloud.org","KYT62PTF5UF"),
  ("NDSENRC147","Jacob Griffin","sed.leo@aol.ca","ILH58RWC6JT"),
  ("GJKWHCX661","Arthur Kennedy","amet@protonmail.ca","FNH37FBS3WD"),
  ("IJPPSLH461","Nicole Powers","commodo.tincidunt.nibh@outlook.ca","CMX78MSM9MT"),
  ("HMDVQBC142","Illiana Dillon","ante@outlook.net","AYM80PXF1IA"),
  ("LNJLVTD847","Dante Anderson","cursus.nunc@google.couk","LYW47ESC4KK"),
  ("DEBZSQY571","Kylan Hudson","curae.donec@google.ca","YMX34WAO2TU"),
  ("QYWERHG333","Claudia Haynes","sed.nec@icloud.net","CMB66FBW3HK"),
  ("IKYLMCU173","William Hardy","tincidunt.nunc.ac@hotmail.edu","WVY86JOD3YM"),
  ("PULBSQH122","Chadwick Fletcher","morbi.quis@hotmail.ca","YLW84LFB5VH"),
  ("SRMMUMY714","Preston Alford","etiam.ligula@hotmail.org","BCQ55DEC6XP"),
  ("TUQABGQ628","Fallon Wheeler","amet@outlook.edu","QUK58CVW6JN"),
  ("MFVKBKY868","Lewis Holland","gravida.nunc@hotmail.com","EHB21JHA4TV"),
  ("YPJDYXS660","Yeo Weber","metus@aol.com","NCR71EOQ2WE"),
  ("PKUMZFH534","Baker Alvarez","a@outlook.couk","LMM32SOV7NK"),
  ("QRSTTQS744","Suki Massey","velit@hotmail.couk","ETV87CWF9QW"),
  ("RGITBCI152","Jolie Parsons","id@aol.edu","VTV65JKM4TK");
INSERT INTO Customers (NetID,Name,Email,Password)
VALUES
  ("XQEDGTV826","Allistair Harrington","ac@google.org","XXA41WHN7LR"),
  ("ODYBDDF131","Quinn Pennington","nulla.facilisis.suspendisse@protonmail.org","PDS73NFR2QD"),
  ("QHVRIXM648","Clayton Good","mollis.dui@google.couk","FXB85DMC3ZQ"),
  ("WJSNMWP827","Leah Flowers","velit.cras@outlook.com","ITL25YVX4VI"),
  ("ARPYHXH648","Jordan Madden","nunc.quis.arcu@aol.edu","UPS87YYN7TX"),
  ("NISVGKU216","Uriel Gallagher","pellentesque.massa@icloud.org","BBL53NPN3OO"),
  ("LDDUHKC836","Lionel Harper","lectus.a.sollicitudin@aol.couk","SWY84YYO3UU"),
  ("CZBEXQM455","Erica Campbell","morbi.sit.amet@aol.com","ANC02TTP6XQ"),
  ("QQTUOXK155","Lars Knowles","in@yahoo.org","KVK85SGS1UU"),
  ("VDWNPPH547","Indigo Thornton","sed.sem@protonmail.ca","LPG75DJH3FP");
INSERT INTO Customers (NetID,Name,Email,Password)
VALUES
  ("TAFZGJA859","Demetria Burch","lectus@protonmail.ca","XDH44JMK9IH"),
  ("DFTXOIL156","Xanthus Tran","sed.dolor@aol.ca","GUS02DDJ1OW"),
  ("KFIKHPQ797","Melanie Craig","ultricies.sem.magna@protonmail.org","UVU70SUZ7JE"),
  ("MRWANZH046","Violet Owen","feugiat@protonmail.org","LRV21NQX5KP"),
  ("DLPVTWZ415","Sawyer Albert","ante.ipsum.primis@icloud.edu","IQG38COG3VI"),
  ("STFVZEJ276","Basil Lee","interdum.enim@protonmail.ca","SES15KLB1KI"),
  ("DCCFVPE643","Yael Avila","orci@outlook.couk","RJP45QGB5KQ"),
  ("CXDSEDL881","Hashim Franco","integer.eu@aol.couk","DSC71ZEI4FT"),
  ("EKSBBUE664","Logan Woodard","aenean@outlook.net","GOY01JPI7DR"),
  ("KTFKOUV275","Jorden Graves","a.aliquet.vel@yahoo.net","HRR25SRE1UD"),
  ("GKFRAOE187","Evan Kinney","aliquet.phasellus@aol.net","IXA18TTT7QA"),
  ("OOXCDCW544","Arden Ball","rutrum.magna@aol.net","YVU35WVM3GW"),
  ("AMCRRDX126","Kyra Ellis","aliquam@outlook.net","ENG16NBW7KT"),
  ("TVDCLVP399","Rebecca Eaton","gravida@google.net","SWG36HLK3RC"),
  ("HFKOTYG521","Lillith Garza","nam.ligula@google.org","LMJ79YCO8PN"),
  ("LAWKEHG344","Ali Watson","luctus.ipsum@icloud.net","FNS60DMC6WB"),
  ("OAMURBI561","Dante Herring","elementum.lorem@icloud.org","EFX16HLI4VO"),
  ("LSFUYON654","Leroy West","semper.dui@outlook.couk","IEA88BCY6KK"),
  ("QIRVSAQ510","Scott Burch","placerat@icloud.couk","VQF54ZRH2GF"),
  ("LTIWIHD213","Stella Mitchell","fringilla.euismod.enim@icloud.edu","MJE28SOU4DF");
INSERT INTO Customers (NetID,Name,Email,Password)
VALUES
  ("BSTUXVK872","Caryn Grimes","tellus.nunc@protonmail.ca","KIE85SKN8QP"),
  ("NVEPOOG547","Jordan Stephenson","cursus.in@yahoo.net","DTM14DMJ4ZO"),
  ("EBGUIHX462","Lara Duffy","diam.sed.diam@hotmail.couk","DOI65MPG1FJ"),
  ("FTKBVWF385","Stewart Burke","nascetur.ridiculus@google.net","QXV65LAK8PW"),
  ("RQMPICS241","Alexis Fleming","sed.dolor.fusce@icloud.ca","KIR65BOC5BF"),
  ("DXPITVB184","Alfreda Marks","proin@yahoo.com","CEM25EIY5PH"),
  ("YNHBOWE862","Kibo Burton","mauris.nulla@icloud.edu","PKF12GBL4YP"),
  ("WXRXIJH232","Hedley French","et.nunc@icloud.com","WIZ67MRY6WU"),
  ("PBLPBWG682","Dean Murray","arcu.et@hotmail.couk","JQF38EAD6FE"),
  ("ONOXJOJ230","Ezekiel Mullins","egestas.duis@yahoo.edu","WJO83ZXY1WW"),
  ("SENMPWS517","Illiana Shaw","ac.risus@yahoo.net","JDW46BJO3HW"),
  ("QYWOKCI381","Tad Mccoy","quisque@hotmail.couk","MSX72YHV6LQ"),
  ("RXQMFOH834","Steven Nielsen","dis.parturient@protonmail.edu","LYC60CWX1FX"),
  ("ZPYNNGY516","Aiko Duffy","ornare.sagittis@hotmail.org","RDQ61MCQ2GY"),
  ("FIHZIYD855","Ralph Mckee","dis.parturient.montes@yahoo.ca","XXU38ZVK4VH"),
  ("OKGXXJK365","Laurel Miles","lorem.ipsum@outlook.net","CPI84EEL1XZ"),
  ("EGPXBEI748","Jermaine Delgado","ante.ipsum@aol.com","PFH65AOG9SR"),
  ("QJWJYER198","Shelby Bell","pretium@aol.ca","SWQ54KOV5MS"),
  ("PIFBHGA637","Guinevere Duncan","at.velit.cras@icloud.ca","LHY14JFU8JS"),
  ("NNSUDIT176","Kaitlin Gilliam","purus@hotmail.com","QMW63DDJ1GS");
INSERT INTO Customers (NetID,Name,Email,Password)
VALUES
  ("IUEQRLY326","Emery Moss","quam.quis@yahoo.org","OFK31LLZ9QK"),
  ("QLZRAIF710","Melissa Burnett","arcu.eu@google.couk","KTW21RPJ5KN"),
  ("ZFXTXVN481","Maggie Livingston","duis.ac@protonmail.net","DKC34KLX6GP"),
  ("RCLERVD846","Arden Patton","imperdiet@yahoo.com","UGT34XUN4QI"),
  ("GHXCJLB535","Kuame Fuentes","ac.metus.vitae@yahoo.edu","EHV08BHF0WS"),
  ("MDQKRXC233","Eve Norton","a.facilisis@hotmail.ca","UMM78RPC1LR"),
  ("PUPFBTO477","Phelan Perkins","phasellus.dapibus@protonmail.net","DAO46YPX1EG"),
  ("HGBTTPI511","Fallon Humphrey","elit@protonmail.net","KEU83MHP1XW"),
  ("VKETSLZ365","Felix Simpson","ut@google.net","FOF33RTH0IG"),
  ("DWJCRQM842","Hollee Tillman","sapien.gravida@aol.edu","WOG47OXF3YB");
INSERT INTO Customers (NetID,Name,Email,Password)
VALUES
  ("NPCRLUE213","Conan Shepherd","nibh.aliquam@aol.couk","AWB21MPQ5GD"),
  ("MXAJFAP425","Norman Gilbert","diam.sed.diam@outlook.com","LRQ56UQM5LY"),
  ("OLKUQGV902","Kadeem Sears","vitae.erat@google.net","VWK78KFK8GK"),
  ("NOSCLJE257","Porter Herrera","tempus.non@yahoo.edu","PJT48VIN6ED"),
  ("CALQVMO965","Brynn Underwood","felis@protonmail.couk","BYJ06VEI2ZF"),
  ("ODHSDZW304","Yuri Welch","vel@yahoo.com","KQN57ALD8GX"),
  ("WWHVODS836","Boris Foster","suscipit.nonummy@protonmail.ca","WXS48PNC3XP"),
  ("JDEXKGC725","William Petersen","enim@outlook.net","HSD38MEX3LC"),
  ("NGGCFYS232","Orli Mcgowan","eleifend@outlook.com","LPT84LPL4MT"),
  ("REOPHOY384","Malik Lambert","justo@icloud.edu","WCQ88DHP7LE"),
  ("PYXOFUQ504","Dahlia Terrell","ut@outlook.edu","BOB48IWH2YN"),
  ("NHXIPKQ647","Bell Rhodes","curabitur@aol.com","FVY93DTW1PR"),
  ("JAILVNE762","Winter Johnson","commodo.hendrerit@outlook.couk","LXP61YGC9LP"),
  ("KRCZSVO835","Colin Meyers","et@outlook.edu","TYZ03DPW5OR"),
  ("YDALJSC945","Chester Elliott","odio.aliquam.vulputate@google.ca","WWL32BLD1WS"),
  ("KBLJZTH316","Brielle Buck","semper.auctor@outlook.com","XYU58VUT7TN"),
  ("HDRFJRJ833","Gemma Hodges","aliquet.diam@aol.couk","JOP22ILR5OH"),
  ("VSHAGXI971","Roanna Rojas","ligula.aenean@hotmail.edu","NXY87VYD8NR"),
  ("CWLJURO607","Melanie Harrington","curabitur.ut@hotmail.couk","LFU51RIK1EJ"),
  ("QFELJHW685","Jakeem Goodwin","adipiscing.elit.curabitur@aol.com","SIV64EMI6XH");
INSERT INTO Customers (NetID,Name,Email,Password)
VALUES
  ("SCPRZKV316","Carissa Pena","dignissim@yahoo.org","KJG71YPH3XV"),
  ("YIWLQCR737","Gemma Stein","at.iaculis@outlook.ca","RTX62TXX6BY"),
  ("OVBOXIF951","Lev Bradford","ac.mattis@protonmail.com","BFT83UOC7IX"),
  ("BRGKJSI322","Bertha Day","consectetuer@hotmail.org","FNH35KGR2SB"),
  ("GELJJFE761","Garth Wilson","in.dolor@aol.com","IJN33OTU3ND"),
  ("JCOVBWJ899","Imani Turner","diam@protonmail.edu","NLE85SYM8WB"),
  ("KHWUCXU929","Brittany Cardenas","mauris.aliquam.eu@protonmail.edu","MCD61PKZ2HL"),
  ("DYQGTVV651","Libby Bradshaw","ut.tincidunt@yahoo.net","MXM77PUP0DD"),
  ("UFSVTFW543","Omar Casey","interdum.nunc@yahoo.com","NBD29DMV9WO"),
  ("XIWRJIV192","Levi Paul","quisque.imperdiet.erat@hotmail.couk","LST53IXD5FE"),
  ("WUMXRTU188","Chastity Mcdowell","facilisis.lorem@protonmail.com","TSF44GDQ1ZN"),
  ("XLNISFN386","Liberty Ward","blandit.at.nisi@outlook.com","XXH64BSR5EF"),
  ("YFDCHPP146","Holmes Thompson","luctus.sit@yahoo.ca","XJT87WRL4QZ"),
  ("CDSRFCS878","Jason Holman","quisque.ac@aol.ca","HRD53JMR2JM"),
  ("ZVGEZGR345","Chancellor Holden","sed.facilisis@icloud.ca","AQV66QPI8KU"),
  ("BOLORRM621","Moses Mccall","blandit.viverra@aol.couk","CLF06YMS5IR"),
  ("LEYORTK972","Hope Church","tempor.bibendum@hotmail.com","FZE95DGB1SL"),
  ("RFHNETF454","Amos Duffy","sed.auctor@google.ca","FMM50ELS5OS"),
  ("KXONNRT376","Vivien Wong","et@aol.org","SPG65RMB5YL"),
  ("BOXKXDI734","Nissim Banks","mauris.quis.turpis@outlook.ca","BHT32PUK8TV");
INSERT INTO Customers (NetID,Name,Email,Password)
VALUES
  ("GYMQROG868","Genevieve Wilkerson","quis.accumsan@hotmail.com","QRR06AGJ3PV"),
  ("FFMYYQU812","Halee Mcgee","tincidunt.dui.augue@icloud.couk","MSD54AKD8KS"),
  ("DOJBTRT352","Savannah Stewart","tincidunt@yahoo.com","XJE18JKN2SD"),
  ("TTSSQXJ633","Fitzgerald Rivers","enim@hotmail.com","YGZ78XNS6ME"),
  ("BFNJRPY316","Lois Ratliff","arcu.morbi@icloud.net","PCJ86KLY1DX"),
  ("ADBKJSU182","Sage Henson","vivamus.nisi@google.org","IRD84CCO7MX"),
  ("FDYZDDK833","Buckminster Leonard","id@aol.edu","PSI14WJO4BZ"),
  ("WUEUCVF816","Mannix Hebert","semper.dui.lectus@aol.edu","PWU34LXO2AQ"),
  ("OXSLWOT211","Rama English","quis.diam.pellentesque@icloud.ca","HVO25RLS9JB"),
  ("UKLYMWT064","Jael Fletcher","bibendum.ullamcorper.duis@icloud.net","JWU84KMM7NT");
INSERT INTO Customers (NetID,Name,Email,Password)
VALUES
  ("TPVESWD381","Yuri Hogan","phasellus.fermentum@protonmail.couk","FLU54HFH5KT"),
  ("RIIIIYT231","Xaviera Eaton","libero.integer.in@yahoo.couk","DNE34EKY1OP"),
  ("IVXQMPM545","Darrel Beasley","integer.id.magna@icloud.org","RCJ74YKT6LT"),
  ("WYJRMBI110","Byron Huber","enim.nec@outlook.edu","KLQ71KSW8YS"),
  ("BHUDCAY430","Kermit Dudley","est.nunc@icloud.net","BHL41SPI1OF"),
  ("XBIQGZA432","Branden Farley","ante.vivamus@hotmail.net","VGL35EYS8QK"),
  ("IXSPIDT061","Ferdinand Stevenson","iaculis.quis.pede@outlook.edu","LUX84FGP0IR"),
  ("TSYULCW351","Troy Whitley","donec.tempor.est@aol.net","YWU73BKU8CF"),
  ("QPCMIIP646","Blythe Riddle","viverra.donec@icloud.com","YHE35MHU2EW"),
  ("PEQUWBW266","Lance Lane","faucibus@yahoo.ca","MOK54MIH6OG"),
  ("KRNKBYY496","Wesley Jacobs","iaculis@hotmail.edu","GDV39IAH3GF"),
  ("VTPXVAM551","Celeste Burks","id.mollis@hotmail.org","WDJ71TYR4GG"),
  ("XTROPAS767","Daphne Barber","mus.proin.vel@aol.ca","XVW24EXH2MN"),
  ("BEXSVOH461","Madison Andrews","montes.nascetur@yahoo.edu","XEN95ILS5NH"),
  ("YUDGCEB412","Phelan Snider","pede.nec@yahoo.ca","OBI64XFB7HT"),
  ("PMQPFYN632","John Dickson","nunc@aol.couk","DSN78KWG6LD"),
  ("NHLHLHO362","Diana Rivers","tristique@protonmail.com","VKB41HQN7OB"),
  ("FDUFQIL251","Keegan Mcguire","in@yahoo.com","FOT43CUX8VK"),
  ("PRIRDLZ115","Dorothy Cannon","quis@outlook.com","QAI41LMI4ML"),
  ("SEQMNON489","Davis Cross","velit.justo@outlook.net","HDJ01HPU5LV");
INSERT INTO Customers (NetID,Name,Email,Password)
VALUES
  ("EMFCGBH389","Shoshana Fisher","id.blandit.at@outlook.ca","FGB22TDG9SG"),
  ("TDBSTYP941","Cheyenne Fernandez","nostra.per@aol.net","WPY02BLW7DB"),
  ("BYDGRAI419","Mercedes Russo","quisque@yahoo.org","LHU61CPD7SI"),
  ("EMWCEUV950","Nehru Campbell","lectus.a@icloud.ca","HLR42IWP7GN"),
  ("RDKKDQU147","Kevyn Bright","dictum.eu@icloud.org","XMI60YBU8PL"),
  ("XXKVCKC202","Oprah Chan","pellentesque.tellus@yahoo.net","LSK13YTH2MT"),
  ("JMFEPQJ785","Ava Matthews","ut@outlook.ca","MWN61CXQ4JN"),
  ("VMRTNOV711","Felix England","tincidunt.pede@protonmail.couk","QBD48IOY1BR"),
  ("JHPYFRR143","Dale O'connor","eros.nec@protonmail.couk","PHY88UVV6LB"),
  ("OGIDXLF067","Ivor Pollard","suscipit.nonummy@yahoo.org","PPX54DHF1EZ"),
  ("TMSERVJ121","Vincent Stark","et.arcu@yahoo.couk","QHN78EQP2FV"),
  ("FJWHAWE808","Kieran Gray","et.commodo@google.org","PDX75RCW7FC"),
  ("ZBRQYFY513","Candace Bernard","ut.tincidunt@outlook.org","NOY03SLG8CB"),
  ("RGGCWUR288","Ina Hanson","a.aliquet.vel@aol.ca","TJU67TIO6AV"),
  ("MJOMMSN756","Chava Terry","scelerisque.lorem@icloud.edu","EGY34BDV3MU"),
  ("PZVMFTC164","Maya Dennis","ridiculus.mus@protonmail.edu","SWC30CUM1MY"),
  ("JMQVEED676","Tallulah Watson","suspendisse.sed.dolor@icloud.couk","YNW37RFU2LL"),
  ("RKTEKGY272","Jemima Carney","et.magna.praesent@aol.couk","FVR40BKN6MT"),
  ("OBRQEYS465","Ivor Merritt","vulputate.eu.odio@yahoo.ca","GHL80BUI5VK"),
  ("XGMPQSV978","Jesse Irwin","in@yahoo.net","TTP12PKI9VG");
INSERT INTO Customers (NetID,Name,Email,Password)
VALUES
  ("EMSTQFL432","Sebastian Lowe","velit.sed.malesuada@google.edu","ZHV61JTV3WK"),
  ("DFEVXKE164","Maisie Cotton","ipsum.nunc.id@aol.com","EDM93DUF6MO"),
  ("TIVSSRO170","Elaine Snow","at.libero@protonmail.couk","YJL63CIB8QY"),
  ("YYKWSFD787","Isaac Sheppard","est.congue@google.com","RLL97KXO2MN"),
  ("QKUVSHP315","Anika Valenzuela","metus.facilisis.lorem@aol.net","HMY76MUY9WD"),
  ("TDTHXMG302","Mary Chavez","elit.curabitur.sed@aol.com","TIB14XVF6BB"),
  ("PKKEEQV117","Ivan Ewing","dolor@hotmail.com","RJK16COP8EZ"),
  ("FGHHSUF867","Patience Goodman","lorem.eget@icloud.ca","TME62LEE6JB"),
  ("BVIGIVQ186","Kerry Grant","vitae.aliquet@google.couk","MKD56HXG1BG"),
  ("RVJTAIF844","Elvis Small","nunc.quis.arcu@hotmail.ca","ONO17BAG5LP");
INSERT INTO Customers (NetID,Name,Email,Password)
VALUES
  ("LKBIUEB851","Tiger Mcfarland","lobortis.quis@hotmail.edu","WOS25GLC7JO"),
  ("FNLYOFP786","Kylan Jordan","felis.adipiscing@aol.ca","YHW34FSP6PC"),
  ("MFVTILM479","Carl Davis","leo.cras.vehicula@hotmail.net","TTC29ZRB0SU"),
  ("TMYLSWU075","Zenaida Short","lacus.quisque.imperdiet@yahoo.ca","GYU03DDT9CD"),
  ("YNGZFSG987","Reed Keller","in@google.ca","TSI49ETX5MS"),
  ("MMYAKIO454","Mechelle French","in.mi.pede@icloud.org","HVW45KYG2OY"),
  ("WDEXXHJ222","Cyrus Cruz","risus@hotmail.com","DRC88JBQ7DH"),
  ("XQLJSHJ536","Keefe Rowland","sed.eu@aol.couk","HWN23CMF0JT"),
  ("JOTOZXJ300","Jessica Mendez","vulputate.dui@outlook.com","CDH23YDW5CE"),
  ("QYPXLLQ813","Alexandra Knowles","dui.semper@outlook.net","HQQ71TBX0GM"),
  ("TGCIWVG997","Raymond Holmes","lacus.mauris.non@aol.org","LYD32OJR4OW"),
  ("NGUPCKS209","Kalia Mcmahon","habitant.morbi@protonmail.edu","CTH61UZI3JD"),
  ("DDEMZFH892","Otto Jackson","eu@google.couk","JLT80HXH4FS"),
  ("KCMOHWO216","Naida Carpenter","suspendisse.dui.fusce@google.ca","TWU46TGU8RJ"),
  ("XCYUXJM685","Nash Rutledge","lectus@yahoo.couk","BFF41VJB2VI"),
  ("QVNHTJK708","Sharon Beard","leo.vivamus.nibh@google.ca","BCM49WES6ZU"),
  ("YRJNNFF515","Priscilla Delaney","magna.sed@protonmail.ca","OWJ77OFF7JQ"),
  ("VJIYQYX775","Yael Hull","augue.eu.tellus@icloud.net","SHJ58LYL1DB"),
  ("PSRKEYO558","Lacey Fuentes","ultrices@yahoo.couk","PWM34DQO5JD"),
  ("HZCRZSL081","Robin Barr","dolor.sit@yahoo.net","KCW52UNV7BK");
INSERT INTO Customers (NetID,Name,Email,Password)
VALUES
  ("ETVUVMO917","Farrah Goodman","sapien.gravida.non@aol.couk","YZI12GOM6CZ"),
  ("RJJMOZO021","Alexis Faulkner","sem.magna.nec@aol.com","LUO33IDB6AS"),
  ("XENOLGR051","Dolan Harper","vitae@aol.ca","MID43DFN1SO"),
  ("AIBQMMH783","Erich Knox","nibh.enim.gravida@icloud.org","KZT45JAL8WN"),
  ("MFEAXSD938","Ishmael Harrell","aliquam@protonmail.couk","LGY44NGT8BR"),
  ("RZZKKVU714","Talon Campos","odio.semper@outlook.com","JTR83AMI7AR"),
  ("IKYOHNI772","Anthony Compton","vulputate@aol.couk","DKE65WYZ7IK"),
  ("LKQWEMM521","Martena Mathis","sodales.nisi.magna@yahoo.couk","YWP58HJY2DQ"),
  ("YWUMJWE479","Cleo Parsons","nunc.ac.sem@google.org","OSY70LMM4WN"),
  ("BXXPYSN668","Shoshana Trujillo","interdum.sed@google.edu","PJO13RNL1EF"),
  ("LUFTLUJ714","Murphy Holcomb","amet@google.edu","VMD04OBP4OH"),
  ("MWBBAQP042","Gretchen Avery","velit.egestas@outlook.couk","PPH98FUP4US"),
  ("GSSUEYK400","Arthur Murray","id.erat@google.couk","ZES69ZWT1BK"),
  ("ODMQWKL728","Lysandra Justice","non.luctus@icloud.edu","QFX95FXB4QM"),
  ("PVLCFPX811","Charles Zimmerman","in.dolor@yahoo.couk","MMD87VIV1ZF"),
  ("WAVMGOH735","Jordan Schwartz","viverra.maecenas.iaculis@hotmail.ca","UZU34EVF7TT"),
  ("HCEIHVS513","Randall Roberson","ipsum.leo@protonmail.couk","ORS33IZX1XA"),
  ("GGJPFMU544","Wanda Molina","sapien.aenean@hotmail.com","BBT68SDC3KL"),
  ("COXFTLT697","Jeremy Black","aliquet.phasellus@icloud.net","HUG13ONW1KA"),
  ("FXSEPKK135","Beverly Haney","sed.pede@aol.edu","FWQ35ICU1IJ");
INSERT INTO Customers (NetID,Name,Email,Password)
VALUES
  ("AGHVXBJ274","Mari Valenzuela","nisi.mauris@protonmail.net","GUW74CAU3DF"),
  ("JBOKQUS686","Scarlett Brooks","enim@google.edu","HDQ32CTT5YM"),
  ("ONOBOFB413","Jesse Sharpe","hendrerit.consectetuer@aol.edu","VVB34KPN4RQ"),
  ("HMBQJIN122","Noble Ramos","donec@outlook.com","UUY36ZIR2AT"),
  ("XLHFQQR494","Tana Hodge","ut.sem.nulla@icloud.net","VLL67CPK8WQ"),
  ("CSSQXGG444","Salvador Melton","vel.turpis@yahoo.net","IPR46TZJ7KQ"),
  ("MWIPJWH658","Christopher Mueller","enim@icloud.com","YLU72LWL6CB"),
  ("HKMETRX413","Walker Gillespie","dolor.nonummy@protonmail.edu","GWR36QND6DD"),
  ("JQPSHWB612","Graham Mathews","amet@aol.net","XST67NIW6SY"),
  ("NAMSYWN363","Walker Wooten","ac.sem@aol.com","EBR28TEV5CL");
INSERT INTO Customers (NetID,Name,Email,Password)
VALUES
  ("CLRDREI835","Yeo Russell","sem.vitae@outlook.edu","BUO06QKF8KT"),
  ("QCPJSPF044","Cathleen Wilkins","metus.facilisis.lorem@google.ca","DPR71UKU1RM"),
  ("XNBMQEJ984","Alvin Jenkins","ipsum.porta@icloud.net","WNH94PME9VZ"),
  ("UXTWTZP322","Shoshana Melton","nunc.sed@aol.org","LTO30CNR9KO"),
  ("PVNEBNH364","Abigail Bowen","cum@google.net","SME34KMN5SP"),
  ("EIIBHCT411","Stella Cervantes","risus@protonmail.net","BZA81UUM3HX"),
  ("HEYFMQP131","Jin Haney","placerat.eget@yahoo.edu","VSB21VVC1WB"),
  ("VKITGWV811","Ivy Grimes","ligula.eu@google.ca","KUL38CSZ1FU"),
  ("TMUQXTW627","Hillary Barr","tincidunt@outlook.couk","WCD47CXO4PM"),
  ("IMNWIKS823","Melyssa Erickson","gravida.aliquam.tincidunt@yahoo.edu","ZOY66IBH6HN"),
  ("DJVBLVR858","Aladdin Mccoy","elit@yahoo.net","SWO76SAX4GN"),
  ("GDITJPL332","Bevis Galloway","suspendisse@aol.couk","ECH78GMP1GN"),
  ("DEAMBNQ526","Moana Garcia","ligula.aliquam.erat@google.edu","GSP05CDB2SS"),
  ("VBXPRCI462","Cassandra Rutledge","nisi.mauris@icloud.couk","JHB79VMT9FX"),
  ("RAXKKLS855","Brennan Gutierrez","diam.sed@protonmail.com","IET74UPE4IX"),
  ("WFSKBDN557","Elaine Randall","per@aol.edu","KHB38RVR0JX"),
  ("FXMXVUK519","Erica Downs","a.enim.suspendisse@yahoo.ca","YFG67ZCR4QY"),
  ("RFUXZPC589","Sawyer Pacheco","augue.ut@protonmail.net","JIE27JDC8LQ"),
  ("KYQMMIK244","Colorado Castaneda","in.molestie@icloud.org","YAT94OKW6IJ"),
  ("FCJDKEW448","Jemima Lamb","pretium.et@yahoo.com","XGL62WCM0MS");
INSERT INTO Customers (NetID,Name,Email,Password)
VALUES
  ("AUKQCWB265","Ivor Santiago","convallis.ligula.donec@yahoo.net","DKN25MLT2RV"),
  ("WXLLWBC134","Amy Shields","proin.vel@outlook.edu","GJP62VNQ2VI"),
  ("CRDIALR771","Bruno Shaw","egestas@hotmail.com","YBH15OKL7QH"),
  ("MRWHYPZ885","Emerald Mcbride","non.enim.mauris@protonmail.org","KWP11BKR3WR"),
  ("YLNPECF164","Michael Marquez","scelerisque.neque@icloud.couk","CWX68XKQ8AT"),
  ("UCHGXSY268","Jena Petty","sollicitudin.orci@yahoo.net","NNT55WEP8JR"),
  ("DNEHHDU271","Byron Price","justo@aol.org","VEQ04PWK9RQ"),
  ("QTYARSM752","Carter Aguirre","augue@outlook.net","QGI39GEM6HR"),
  ("IUHWOKZ856","Joy Schwartz","risus.donec@outlook.net","VVR03PWT7NI"),
  ("VUTJHMU819","Nehru Mclaughlin","luctus.ut@google.com","HVM81SJH9FQ"),
  ("LDEIOHO997","Germaine Gutierrez","nibh.vulputate.mauris@protonmail.ca","LVM49UNL6SY"),
  ("JNKHXKW163","Jelani Frank","parturient.montes.nascetur@icloud.net","HSH17GRR8SD"),
  ("TMIIHHO133","Melyssa Chapman","placerat.eget@protonmail.net","ZME27QLR7EF"),
  ("JPGMOIL761","Calvin Justice","et.magnis@outlook.net","QSL05MIF6XH"),
  ("LCTYJMY774","Uriel Tate","nisl@yahoo.edu","KVB27LIM6CR"),
  ("YOUVYIK869","Mohammad Ball","scelerisque.lorem.ipsum@google.edu","RBN19GVP6BB"),
  ("KXQXUSU886","Addison Harvey","luctus.et.ultrices@yahoo.couk","IWY12AEW1YW"),
  ("YOMVTZT290","Edward Lester","dignissim.lacus.aliquam@icloud.couk","AIB32ALQ4CF"),
  ("GYJIDVK623","Christopher Myers","eu.turpis@aol.ca","FED56GUI5EA"),
  ("JFMWGKD474","Sharon Best","sapien.cras.dolor@hotmail.com","ISK41XKW9OV");
INSERT INTO Customers (NetID,Name,Email,Password)
VALUES
  ("ZIMWWTU573","Aquila Mooney","orci.ut@aol.couk","OVA69CPX4GB"),
  ("HRGHNQO671","Stone Payne","at.iaculis@google.edu","ZSO76WDX1PH"),
  ("TVLQNMU138","Orson Torres","tempor.erat@icloud.com","XKO38LEY4NO"),
  ("RJSENFT158","Burke Foster","cras@protonmail.ca","TGL08UWT1DM"),
  ("FPVFQXM293","Rudyard Wilkins","orci.donec.nibh@protonmail.edu","QRK64YPX1DF"),
  ("UTIGHEL572","Kenneth Norris","dictum@outlook.com","DOM73WTU2WJ"),
  ("XIXKFON246","Griffith Silva","nunc.lectus@hotmail.com","KGW37CTY1QR"),
  ("VXHYENN385","Giacomo Preston","non@hotmail.org","GXB93UWY9JR"),
  ("FMBHVHP713","Caldwell Harrington","fames.ac.turpis@protonmail.net","IOO87SBS0WC"),
  ("VMAGBSK527","Ahmed Bryant","non.bibendum@hotmail.edu","FEE16SIM6CR");
INSERT INTO Customers (NetID,Name,Email,Password)
VALUES
  ("VVRTZIO664","Reece Pope","metus.eu.erat@hotmail.com","TDQ14JGS3GW"),
  ("PECSZUO182","Berk Noel","quam@outlook.edu","ASQ52TVE2XX"),
  ("MIITBEO491","Devin Morris","proin.dolor@outlook.couk","JAR73LTP8TW"),
  ("YFRNGGI644","Michael Wyatt","ut.cursus.luctus@hotmail.edu","FES47EIL2OY"),
  ("WUUEMND450","Bree Powers","libero.proin@icloud.net","UBB80MXF3XP"),
  ("KLAGHEL444","Fay Porter","enim.sed@outlook.org","VCE76CIN5JF"),
  ("CDNCPCD540","Farrah Vinson","ipsum.dolor@outlook.edu","ESH21QVG3TB"),
  ("TTSKQEO446","Ian Allison","vel.quam@yahoo.ca","GTX77LYU8KZ"),
  ("VQRNGMU554","Eagan Hunter","aliquet@google.com","TEY19GDL7SL"),
  ("DGESTSP446","Cameron Watson","ipsum.primis@protonmail.org","UUK55BXO5VO"),
  ("VQRKLPW868","Clayton Navarro","arcu@aol.ca","CFW63UIB0FC"),
  ("OIPFRQU786","Dara Rowland","aliquet@protonmail.net","WSQ37YFQ8XT"),
  ("JMRKATT436","Oren Curry","sit.amet@google.ca","JDI15HYT4YA"),
  ("IFNQXVJ830","Barry Nelson","enim.diam@aol.com","DYI61FJP4XH"),
  ("NIOPFUR055","Mohammad Vazquez","quisque.varius@hotmail.edu","BYX84RZJ0XB"),
  ("JLHRIPO472","Stacey Weber","tempus.mauris@icloud.org","TIP64UNJ5FS"),
  ("FHMVMMG441","Hayfa Erickson","fusce.aliquam@aol.net","CFO72VTF6FD"),
  ("JMJSHSF210","Ignatius Little","nec.quam@google.com","KTF48IQT3NM"),
  ("XYYZDEJ641","Ryder Griffith","mauris.sapien@aol.org","DSC23FCW2UR"),
  ("NHZIRIU838","Madeline Maynard","molestie@aol.net","NGM68LST2ZP");
INSERT INTO Customers (NetID,Name,Email,Password)
VALUES
  ("UHYOBWK621","Camille Sawyer","dolor@protonmail.ca","KDV62XLE4JX"),
  ("JBNEOCB853","Jenna Carrillo","libero.proin@hotmail.net","ILC17DUS0BY"),
  ("JGNQMHW115","Price Fulton","ut.eros@google.org","RQU07YLL2JC"),
  ("ULXOPJL167","Arthur Frank","parturient.montes@aol.net","JLO14SJA1LI"),
  ("MWLWOOH678","Bryar Carr","dictum.mi@hotmail.ca","QWY42FLX4UO"),
  ("MRNHVBG438","Wayne Barnett","blandit@hotmail.couk","SWZ21LSW3LP"),
  ("XVPHRRN242","Talon Reynolds","et.risus@icloud.edu","RLY35HGS4AM"),
  ("WEMZMUI336","Helen Donovan","magna.nec@outlook.ca","LCD60MID3TV"),
  ("XJPGSUO814","Ila Ramsey","vestibulum@protonmail.couk","QDH36GSU3RW"),
  ("OFQIFQZ837","Uriel Morris","duis.gravida@icloud.couk","NBC23TDN1GI"),
  ("OAGCLGQ302","Lyle Stevens","donec@aol.org","MIN37IHE5MX"),
  ("QBHJEJQ067","Angelica Garner","nulla.interdum@outlook.net","GLJ46NNC4CL"),
  ("WOWWDDY352","Hadassah Weber","elit.nulla@icloud.org","WTW00SYA6HB"),
  ("SCUWMOV443","Cooper Rhodes","blandit.congue.in@google.net","PTX38KGS5GI"),
  ("KHHLWFP326","Courtney Trujillo","sed.malesuada@google.ca","LWH12HAK8KS"),
  ("TXNHBFT213","Jarrod Newton","quisque.purus@aol.edu","ATG57OTQ5GP"),
  ("RCKEHLQ546","Joy Harvey","pede.ac.urna@yahoo.couk","IQH46UOR3EQ"),
  ("YNFJNGS603","Nicole Lara","pede.nonummy.ut@yahoo.ca","HTJ87BIB2CJ"),
  ("JERZETP716","Barrett Wood","tempor.lorem.eget@hotmail.ca","ROP32WXB1EB"),
  ("IIFVTYF463","Venus Shannon","ante@google.edu","NEF73WXN0DY");
INSERT INTO Customers (NetID,Name,Email,Password)
VALUES
  ("RKTGISD536","Kennedy Stephenson","vel.faucibus@hotmail.edu","MCJ45XYU8MO"),
  ("VJOKCHQ477","Harper Hurley","vivamus@protonmail.edu","SHH66NDJ7DE"),
  ("PELXXGF536","Paloma Koch","suspendisse.non@outlook.com","LED83YBK3WW"),
  ("OUNXXFX883","Dillon Sloan","venenatis.a@yahoo.net","ZID15YFM1QY"),
  ("QBSOPID514","Ashton Bernard","ligula@google.com","PTU84EMH4LX"),
  ("XCYUOMV722","Stephen Whitney","elit.a.feugiat@icloud.edu","LIM75UWB6TT"),
  ("OSBYPGN750","Halla Ray","torquent.per@protonmail.net","MSV71LWI6SX"),
  ("IQIHNJV566","Dexter Malone","maecenas.iaculis.aliquet@google.com","ENZ57TYQ1FT"),
  ("MLKWCOK101","Joel Barker","egestas@google.couk","GSB47PRH1NJ"),
  ("GBWKGIT571","Carl Prince","vel.vulputate@google.couk","MVT30FII5KR");
INSERT INTO Customers (NetID,Name,Email,Password)
VALUES
  ("DQILOVW286","Ralph Walls","sed.eu.nibh@yahoo.net","OOL99SIO1QI"),
  ("VCJWKOQ852","Cleo Foreman","purus@aol.com","XOH43SLK2TV"),
  ("CPVKRII328","Gabriel Cote","aptent.taciti@icloud.ca","RYB55XIK0GE"),
  ("HWSMNIX481","Vivian Hicks","ac.libero.nec@icloud.couk","NFX59LGC1WN"),
  ("FNYYRLV843","Ivory Soto","nibh@protonmail.edu","JUF84FBK6BH"),
  ("HBJAHOW459","Rhona Nixon","montes.nascetur.ridiculus@google.ca","WJI81KEC9BX"),
  ("EXNSKKK528","Donovan Hunt","fermentum@outlook.edu","AUG79YEF1GD"),
  ("ZUHDAIX275","Tyler Hickman","libero.dui@aol.com","TVC74QKV3BS"),
  ("QKLHSRH841","Roanna Shaw","cum@google.ca","SVH33LKX6IR"),
  ("JXNBLRN462","Lois Manning","nibh.enim@hotmail.com","IJO41HUP8MK"),
  ("CXGUMPI425","Neil Battle","vivamus@google.org","DVK67VWG0EH"),
  ("SYBFJLX785","Karina Ewing","mauris.a.nunc@yahoo.couk","RLU77GNN1BG"),
  ("WCSJHGL750","MacKenzie Sargent","euismod.enim.etiam@icloud.edu","KGN47PYG4BQ"),
  ("HOJOGRB226","Mariam Hopper","et.magnis@protonmail.ca","UYC82LTW8QQ"),
  ("FXKAYFN161","Theodore Hensley","ipsum.leo.elementum@yahoo.com","IXI87DBH6FQ"),
  ("CZJINFW939","Scott Walters","ut@yahoo.edu","XWU61JNO4HW"),
  ("ESORHLU788","Francesca Sims","pellentesque.tincidunt@protonmail.edu","HTC47ZQE0UW"),
  ("LFJMQXO652","Cheryl Pierce","justo@google.ca","OHL44KCP2KF"),
  ("ORPMCYL246","Ashton Compton","urna@aol.ca","UDT40QQL9BF"),
  ("VCPBUNV460","Irene Soto","ornare.in@google.ca","YTQ45RWU4SD");
INSERT INTO Customers (NetID,Name,Email,Password)
VALUES
  ("PGJIVLF083","TaShya Flores","tellus@outlook.ca","MTD25MDX2BK"),
  ("WJLDVTO162","Whoopi Mckenzie","placerat.orci.lacus@google.org","QSI21VHK5TJ"),
  ("DCVLCMF123","Lila Dalton","eleifend.cras@aol.ca","NHO96LHO7SO"),
  ("TUOQISH518","Imani Cortez","iaculis.quis@protonmail.org","ZMU59DUJ7ON"),
  ("WCPIRZT803","Peter Alvarado","sed@hotmail.com","RHQ22SOW8EI"),
  ("KCOZVAU873","Rigel Wynn","amet.nulla@google.com","GIX74ESF1UY"),
  ("UQPSCWF305","Mollie Hooper","dolor.donec.fringilla@hotmail.edu","TFY78BTU6AE"),
  ("SBCXIAR376","Nita Hicks","suscipit.nonummy@outlook.couk","FQN14SEC2XX"),
  ("IMNRMIG401","Adena Jensen","risus.at@outlook.edu","QOD41SVO8CW"),
  ("VVMLTBI548","Alma Alexander","mi.aliquam@protonmail.net","SOF17DJM3NG"),
  ("HIMIUBE624","Caesar Landry","parturient@aol.net","OBJ67TYI8YX"),
  ("FUODYMM209","Omar Franks","elementum.sem.vitae@outlook.edu","TPO59IKU4XW"),
  ("NSWEVVC448","Mira Morin","purus.maecenas@icloud.couk","CSH15ZXT6WP"),
  ("KXIQGFG116","Jael Carson","mus@outlook.org","HWL81JWS8KE"),
  ("VWXWDJT453","Caldwell Richards","ac.risus.morbi@yahoo.edu","RZH68CPV5DT"),
  ("AKOTQKI367","Carter Hogan","lacus@protonmail.ca","FOR67WQZ8KE"),
  ("RSVLJXB684","Len Perez","dictum.ultricies@icloud.net","XCP44WWC1XI"),
  ("BMPMPJB426","Sophia Donovan","neque@aol.edu","RXM56UGQ3DE"),
  ("PQBBHJK211","Jameson Hanson","pellentesque.habitant@protonmail.com","UYP73YBP5RW"),
  ("ROWGVMV155","Olympia Cortez","egestas.nunc@protonmail.edu","LPC42QSU6UP");
INSERT INTO Customers (NetID,Name,Email,Password)
VALUES
  ("BQXFFFX674","Jemima Lewis","eget.magna@aol.net","FIP48VUB5CV"),
  ("UFDPFJU937","Candace Barron","lacus.vestibulum.lorem@aol.com","RWS31LZI8OW"),
  ("ENRYCSM375","Sawyer Deleon","non@google.net","UEN64ROA0UC"),
  ("VMDMNEX758","Cairo Gilliam","est.tempor@protonmail.org","JQV30EKX0WI"),
  ("FEFGJPV141","Leroy Estrada","habitant.morbi@google.ca","DXN43VLR2GD"),
  ("AXFBPFT265","Daquan Workman","donec.sollicitudin.adipiscing@icloud.org","RWE71SWH1VF"),
  ("FMRPUEI834","Halla Hutchinson","urna.et@google.edu","JRM88KRQ3TY"),
  ("QFQPXDY600","Wing Farrell","neque.pellentesque.massa@aol.org","HRN22MCE6OP"),
  ("WVPUUJA188","Rama Mcneil","diam.pellentesque@hotmail.com","YLR12GJP5MZ"),
  ("ANJRFST739","Rebecca Boone","congue@aol.com","EML84JIK2HZ");
INSERT INTO Customers (NetID,Name,Email,Password)
VALUES
  ("LRHVUJL426","Tashya Alvarez","mollis.integer@outlook.couk","CWY89FHN6ZM"),
  ("MEYFREG275","Yoko Mosley","maecenas.ornare.egestas@hotmail.couk","VOG22UYN0JX"),
  ("EBCGWME855","Angelica Albert","per.conubia.nostra@yahoo.ca","IBG17ZLQ6MJ"),
  ("JIVKLHL761","Solomon Hicks","risus.varius@icloud.edu","FRJ43QZR8EP"),
  ("CVSGGHC550","Summer Roth","dui@hotmail.ca","PRL88SBM4PW"),
  ("JVITSHA362","Imani Ross","magna.duis.dignissim@icloud.com","EHV23RTR4RE"),
  ("TSTAVJD576","Erich Madden","in.dolor@google.edu","EIF01NOP6MU"),
  ("QLCUQMH279","Rebecca Stevenson","congue.turpis@google.net","TPQ47BCW8RI"),
  ("CWSRSQK212","Sopoline Fischer","condimentum.donec@yahoo.edu","AKQ83AKD6NY"),
  ("JKCXJHS601","Keegan Knox","dictum.eleifend.nunc@yahoo.edu","EKJ67KRF2YN"),
  ("LINOBKO436","Buffy Ingram","nec@hotmail.net","UNV17XJK6VV"),
  ("LCYBQBC277","Murphy Rodriquez","ante.dictum.cursus@outlook.com","GJR04HMB5UB"),
  ("JOBQGPK317","Brielle Chandler","ac.sem@icloud.ca","ZHP01DIY2VG"),
  ("ODEFUEL675","Jonah Dodson","massa.mauris.vestibulum@google.com","IFJ54DIB8MW"),
  ("HTDZHWT115","Kennan Holmes","egestas.lacinia@aol.couk","KEO72HMX6KO"),
  ("KIHKDKM317","Samantha Beasley","auctor.vitae@hotmail.org","ILO58NMK2XF"),
  ("PLETEFE561","Latifah Freeman","nulla.facilisis@yahoo.net","JQJ03TRR3RD"),
  ("GKDZRNJ140","Ezekiel Davidson","magna.cras@aol.net","NSK27CVG5PU"),
  ("KDYLMGB752","Jordan Pacheco","nonummy.fusce@hotmail.org","TND24RLL1WR"),
  ("TMJBPWK116","Paki Howell","sed@yahoo.com","KOV58LKY3LJ");
INSERT INTO Customers (NetID,Name,Email,Password)
VALUES
  ("VLOKUDU751","Jermaine Alvarado","nunc.id@hotmail.com","SYO26GNG5PO"),
  ("YTJATBB478","Carlos Wallace","auctor.nunc.nulla@hotmail.ca","MXK83IXZ2VN"),
  ("FHHYLXP185","Kelsie Sanchez","ipsum@hotmail.com","LPH32CIT2FW"),
  ("ZGTCRIJ184","Eagan Meyer","risus.nulla@protonmail.ca","XWI16UTO9II"),
  ("KICXIXF206","Tad Valdez","et.magna@icloud.edu","RRE63WYC5WP"),
  ("FGSBDJC893","Ulric Chandler","duis.ac@icloud.com","XXK42GAU6TG"),
  ("KQYWIBD947","Daryl Boyd","sed.nulla@outlook.org","VAJ36GMY7UL"),
  ("ZIXJWWU501","Leila Woods","elit.aliquam@hotmail.org","VMH92JFB5JZ"),
  ("TNDIPJR156","Sasha Pugh","egestas.urna@protonmail.ca","SNP61KWU2QI"),
  ("MKHWKSJ324","Reuben Cortez","ut@outlook.org","RNU61FBC5XQ"),
  ("KEULJQK364","Bryar Lester","pharetra.quisque@protonmail.ca","VFV91ENI8AE"),
  ("DDDNVQD384","Byron Hicks","ligula.aliquam.erat@yahoo.couk","RIH70FQK5YL"),
  ("GJKDDOE556","Jonah Wolf","lorem@protonmail.edu","OUK06HBH4SD"),
  ("IOCYQBY683","Stacey Mcleod","donec@outlook.ca","GDN11GUS8UC"),
  ("YIENWXF342","Mannix Johns","vulputate.dui.nec@protonmail.com","XSO34EHU8FK"),
  ("MTVUFTI743","Francesca Holden","sociis.natoque@yahoo.org","NDM29OYB8XG"),
  ("BTVPBJN451","Quinn Savage","nulla.vulputate@hotmail.org","FXB19OTV9AG"),
  ("WYBPOYE816","Amber Watts","ac.nulla.in@aol.ca","BKH86PIS3MP"),
  ("OWHCTHC287","Harding Miles","sed@outlook.com","DIF14QTD1HK"),
  ("PZOYZPT132","Leilani Vasquez","eu@icloud.couk","LYA55CDB0AH");
INSERT INTO Customers (NetID,Name,Email,Password)
VALUES
  ("PGVVWXW162","Fitzgerald Luna","eget@icloud.edu","REP48CJW3VN"),
  ("UBHHLJJ368","Cody Carter","ut.tincidunt.vehicula@outlook.couk","KHF62SWH8FN"),
  ("YVVHXHM683","Hedley Roberts","taciti.sociosqu@icloud.couk","BSD19NMR4GE"),
  ("TUFLQDW169","Kenneth Duffy","vel.convallis@aol.com","CIC94OHW7FI"),
  ("MSCVCXD666","Aspen Skinner","ac.metus@yahoo.org","HSQ25CIV1WZ"),
  ("YFOCHYK746","Zeus Gallagher","purus@protonmail.org","RCX90TDE6SV"),
  ("LOLDXMB468","Randall Peck","lacus.varius@google.couk","CRP06OUT1BQ"),
  ("IJXQMIN683","Tana Ruiz","mi@aol.ca","CZJ42UFD1XG"),
  ("ISQRDRL875","Trevor Craig","sagittis.placerat@yahoo.com","PDC23HIK5JO"),
  ("FGEAWFF452","Keith Foreman","dui.suspendisse@yahoo.couk","RXX28SDX0CG");
INSERT INTO Customers (NetID,Name,Email,Password)
VALUES
  ("FXLIZAP714","Wilma Lamb","at.augue@icloud.com","IBM05NXO6DF"),
  ("RJGJSBB861","Chester Douglas","enim.non@icloud.com","SIE11XSB3VF"),
  ("LBKTGJT697","Jescie Bentley","consequat.dolor@protonmail.edu","AJI94LVQ8VW"),
  ("CYVFTFS640","Winifred Knowles","vivamus@aol.couk","FVM21YGY8WU"),
  ("HYGMFOV584","Neve Olsen","nisi.cum@protonmail.com","RLY18BRQ9WE"),
  ("IZJZDXO435","Erin Wolf","ultrices.sit.amet@google.couk","WKW76FDF2HT"),
  ("EQPYQBZ658","Cade Bryant","quisque@hotmail.ca","SQS51SPQ3XN"),
  ("XNQKBKG697","Jarrod Collins","ut@icloud.com","VCX07ZHG1SR"),
  ("UTRSCSI614","Hermione Hurst","mollis.integer@google.edu","HXR24LPY4BB"),
  ("MYHXGHI121","Vance Houston","a@icloud.edu","SJH72WIH4JE"),
  ("XHHMFMW953","Bree Stanley","aliquam.adipiscing@hotmail.com","QPP11JUE7LY"),
  ("UNADKWP028","Alana Hester","scelerisque.neque@yahoo.net","LJU87XKB8WE"),
  ("TXDVJLH828","Clarke Goff","mi.enim@icloud.ca","IHL27JMW7VY"),
  ("EHHFOGS476","Ifeoma Faulkner","magna@icloud.org","NPY27PCV8MO"),
  ("YXDRYKR666","Alden Day","fusce.mollis@protonmail.couk","TWR26UOW5DO"),
  ("XXXQYXO303","Brooke Mccall","auctor.velit@yahoo.org","TNR64WJG6PF"),
  ("BJGWIOR855","Isabelle Berg","augue.ac@outlook.net","GXD92POV8MP"),
  ("MCJOKSD156","Demetrius Carroll","justo@icloud.ca","EGF62LLU5QB"),
  ("PIITERI633","Alvin Crane","ac@google.ca","FRH63TAF1LR"),
  ("ZRCCMCK234","Dorothy Galloway","velit@outlook.couk","TZC11BFD8IB");
INSERT INTO Customers (NetID,Name,Email,Password)
VALUES
  ("GXJWSDD628","Yuli Craft","nunc.ac.sem@icloud.org","ORX14SGC4KU"),
  ("XRUKHJK787","Adena Briggs","sit.amet@icloud.edu","IWI04CBN8PX"),
  ("WCQIJGU421","Avye Downs","congue.a.aliquet@yahoo.ca","GFI06WIT2DB"),
  ("OIWXSEK866","Graham Yates","felis@icloud.org","SXV63UIF7LT"),
  ("GAVCYDN566","Charissa Cook","lorem@icloud.net","NRF91LTE9ZZ"),
  ("DBTERVR484","Donna Bonner","tellus.non.magna@outlook.com","HFF82WWE2JI"),
  ("SSSRTLM108","Patience Gordon","sit.amet.risus@protonmail.edu","DTQ27DPW2FS"),
  ("HLWETEO681","Zeph Chandler","sagittis.placerat.cras@google.couk","BEF19YAV7VN"),
  ("UXQTXDX261","Gisela Mitchell","arcu.imperdiet@protonmail.org","PIY46MXY1DL"),
  ("VFBVQSD316","Meredith Gomez","mus.proin@google.couk","SGL18DPE3AH"),
  ("JCIMQKW894","Francesca Jimenez","donec.consectetuer.mauris@outlook.edu","FYL26EBV1GQ"),
  ("SXKMYUS738","Nasim Castillo","nunc.sollicitudin.commodo@hotmail.couk","GEZ70JVG1IZ"),
  ("UFHSBBE764","Cheryl Dennis","augue.ut@protonmail.edu","BRQ67AFL6IU"),
  ("LJIWAGS885","Jerry Hendrix","nunc.sed@protonmail.couk","VTX41GXR1BV"),
  ("KXYVOUH818","Callie Perez","tincidunt.orci@hotmail.com","THY23KMX8BG"),
  ("CJWNMGW567","Leigh Alford","aliquam@aol.com","XMH36CED7OA"),
  ("VPMOFIK211","Dana Browning","a.scelerisque@icloud.couk","GUV51HVO0CZ"),
  ("NAZSCYQ458","Jacqueline Stafford","tristique.senectus@aol.edu","IOR43ZQY7XQ"),
  ("WKRNRNU071","Clio Reeves","magna.malesuada@protonmail.ca","OHV47YCB6MN"),
  ("AJAWQNA165","Ashton Cardenas","nec.urna.suscipit@google.edu","DTL53GTG4PQ");
INSERT INTO Customers (NetID,Name,Email,Password)
VALUES
  ("FNUWPHH344","Kathleen Johnson","tempor.bibendum@yahoo.net","RRP74UJM1UD"),
  ("ZKXNOVY584","Imelda Christensen","libero@icloud.com","GTO38NYS4HA"),
  ("PPEWYVQ914","Whitney Marks","ullamcorper.nisl@protonmail.couk","KPU56CDA6IB"),
  ("EMBNFYV964","Ivor David","elit@outlook.couk","HMI38QHX6RY"),
  ("TQBZCYK888","Marah Guy","tempor.lorem@icloud.edu","MTI30GEM5KW"),
  ("PEVHPQK488","Gregory Calderon","mauris.sit@hotmail.org","HFU21FYJ0GC"),
  ("OSOFYFN083","Price Dodson","lobortis.risus@yahoo.edu","XTD45PLL7NF"),
  ("MJZJGQU137","Clark Delaney","pellentesque@yahoo.net","SXL48FRB2YU"),
  ("DNFGKQV825","Gisela Love","sed@hotmail.ca","BTW97MUM9GS"),
  ("MFYQFQF317","Haviva Mullins","mollis.non@hotmail.edu","RUY13NNT5IO");
